### ISSUE TITLE
Fix the typo on Invidious, on the Github description and the Chrome store page.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [SimonBrazell/privacy-redirect#1]
Those are misspelled as Invideus, despite being correctly written on the README.md and on the Firefox extension description page.

**Comment by SimonBrazell** [comment]
Hi @PoorPocketsMcNewHold, yes I noticed this, fixed it on firefox, but for Chrome I need to submit another build to address it.

**Comment by SimonBrazell** [comment]
Fixed this with a new package upload to the Chrome store, should be live in the next hour or so.

**Comment by PoorPocketsMcNewHold** [comment]
![Capture d'écran Deepin_zone de sélection _20190930163400](https://user-images.githubusercontent.com/13170204/65888648-29f97e80-e3a0-11e9-8531-be963f34cda6.png)
Forgot that one.
