### ISSUE TITLE
If the link to another instance has a trailing slash, the redirection fails

### ISSUE THREAD

**Issue by narFnarF** [SimonBrazell/privacy-redirect#10]
This is a suggestion to help user avoiding mistakes when entering URL for alternate instances. The extension could be smart and ignoring the trailing slash character would.

**Steps to reproduce:**
1. Open the Privacy Redirect popup
1. Enter `https://nitter.snopyta.org/` in the Nitter Instance field (Notice the trailing slash `/` character)
1. Attempt to open twitter.com

**Current result:**
It attempts to load `https://nitter.snopyta.org//` (notice the 2 trailing slash characters)

**Expected result:**
I loads `https://nitter.snopyta.org/` (just 1 slash character at the end)

**Screenshot:**
![](https://i.imgur.com/bXpFFzR.png)

**Note:** My example is about Twitter/Nitter but this behaviour is true for all 3 services.

**Comment by SimonBrazell** [comment]
Yeah I've noticed this, and it has been reported by another user on the FF store. There is currently no validation on the instance inputs so you need to make sure you just include the domain and protocol, no trailing forward slashes. I'll fix this up in the next release.

**Comment by SimonBrazell** [comment]
Also I noticed in the screenshot that you are running v1.1.4, I made a mistake in that release that broke some Invidious redirects as it didn't include the query strings in the redirect, this is resolved in v1.1.5 if you are experiencing that problem.

**Comment by SimonBrazell** [comment]
Hmm actually, I think I forgot to update the version number in that build... as it was a quick one to fix that problem... damn.

**Comment by SimonBrazell** [comment]
Included in [v1.1.6](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.6), which is currently pending release on the stores.

There is now basic input validation which will highlight the input as red if validation is failed, and strip unnecessary characters like trailing forward slash characters on save automatically.
