### ISSUE TITLE
Redirect + 'always open in this container' for the target = 2 tabs.

### ISSUE THREAD

**Issue by jtagcat** [SimonBrazell/privacy-redirect#108]
Quite annoying, I open a link from an external source, for each link, 2 tabs appear.

**Comment by SimonBrazell** [comment]
Hi sorry I'm not sure what you're talking about here, sounds like it's caused by another extension?

**Comment by jtagcat** [comment]
Probably a combination of Privacy redirect, and 'always open in this container' with Firefox Containers.

**Comment by SimonBrazell** [comment]
Did you have any more luck with this? Seems more like an issue specific to the `Firefox Containers` you mentioned.

**Comment by jtagcat** [comment]
FF Containers at some point got 'replace tab' feature. Combining that with 'always open in container' seems to somewhat work. It's slow, it takes quite the time to setup (1.5m-2m per target domain, also the source domain sometimes (not sure on what cases) needs to have it's own container with 'always open in container')

I guess issue is resolved, but very long setup + on each tab open it goes from teporary container to source domain container to target container. This is snappy with <10 domains, but me pasting in 200 tabs to open.. well doing s/source.tld/target.tld/g first changes wait time of 20-30m to few minutes...

**Comment by r-a-y** [comment]
I encountered this recently with Privacy Redirect and Temporary Containers / Multi-Account Containers addons.

Here are some related issues:

- https://github.com/stoically/temporary-containers/issues/483
- https://github.com/mozilla/multi-account-containers/issues/940#issuecomment-364361409
