### ISSUE TITLE
Possibility to only redirect youtube.com/watch links

### ISSUE THREAD

**Issue by jwsp1** [SimonBrazell/privacy-redirect#11]
As much as I like the idea of invidio.us, I prefer seeing youtube's startpage in order to see trending videos list and to get better search results. 
Would it be possible to add an option to only redirect youtube links that start with "youtube.com/watch[...]"? 
This way, youtube startpage (youtube.com) and youtube search results (youtube.com/results[...]) come from youtube while the actual video page (youtube.com/watch[...]) gets redirected to invidio.us.

**Comment by SimonBrazell** [comment]
Perhaps this could be implemented as an advanced setting? Might get complicated trying to handle all the different cases.

**Comment by jwsp1** [comment]
If that's technically possible, I'd love to have an advanced setting for that :) but I can understand if it's too hard to implement.

**Comment by SimonBrazell** [comment]
Tried this out tonight, I don't think it's possible the way you would like it to work, it appears that when you navigate to a YouTube video from within the YouTube site, like after searching or from the homepage, it doesn't trigger the redirect and still loads the video in YouTube. Only seems to work correctly if I open the video link in a new tab. I assume this is because the site handles internal navigation itself rather than using browser links.

**Comment by jwsp1** [comment]
> Tried this out tonight, I don't think it's possible the way you would like it to work, it appears that when you navigate to a YouTube video from within the YouTube site, like after searching or from the homepage, it doesn't trigger the redirect and still loads the video in YouTube. Only seems to work correctly if I open the video link in a new tab. I assume this is because the site handles internal navigation itself rather than using browser links.

That's what I thought. Some websites, like YouTube, actually don't reload the whole website again after clicking somewhere.
Thanks for trying :)

**Comment by SimonBrazell** [comment]
Yeah sorry, I tried, if you want I could include it in the next build anyway so you can at least right click to open videos in Invidious?

**Comment by jwsp1** [comment]
Don't know if I would use it, to be honest. Guess I'll just have to get familiar with invidio.us start page :)
