### ISSUE TITLE
Add Support for Opening YouTube links into FreeTube

### ISSUE THREAD

**Issue by PrestonN** [SimonBrazell/privacy-redirect#113]
Hey there! I'm the developer of [FreeTube](https://github.com/FreeTubeApp/FreeTube).

I was wondering if you could add support for opening up YouTube links into FreeTube.  I already have my own extension that works okay enough though I feel like a proper extension like this would be best for everyone.

To do this on your end, you would simply attach `freetube://` to the beginning of a YouTube link.

`freetube://https://www.youtube.com/watch?v=5uWXfoX1x3A`

Any other specific logic, as far as what happens to that URL, is handled on my end, so hopefully this would be an easy addition to your extension.

**Comment by SimonBrazell** [comment]
Hi @PrestonN sounds good, I think this has been asked for already. 

To be honest I'm finding it hard to get time or the motivation to work on this project lately so this may be a while off but I will certainly do it when I do next work on the project.

**Comment by SimonBrazell** [comment]
Sounds super simple, wondering if I should handle this in the UI though, also what would happen with embedded videos? Guess this could just be a simple option in the settings page to use Freetube where possible but fallback to the selected invidious instance(s) where not?

**Comment by PrestonN** [comment]
What you just described is pretty much how I imagined it would be setup.  I can't offer any embedded videos so using Invidious for that would probably still be preferred.  I'm also not sure if this helps or not but FreeTube is setup to accept Invidious links as well with the same structure as the OP.

No rush on getting it done, just figured I'd log it here for the next time you work on this since I didn't see anything about it.

Thanks for considering it! :)

**Comment by ToughGuyKunio** [comment]
Would it be possible to replace the iframe with html code, something like a grey background and a link that says "open in freetube"?

**Comment by SimonBrazell** [comment]
Yeah that would be possible, that's also similar to something that was requested in the past, a good suggestion I think.

**Comment by SimonBrazell** [comment]
> Also, Simon, take some time off, you've earned it :)

Thanks @ToughGuyKunio 🙂

**Comment by SimonBrazell** [comment]
This should be working now, activated via a new setting in the "Advanced" options tab. Embeds (`sub_frame`) redirect to Invidious as usual while any direct links (`main_frame`) should open in FreeTube.

FreeTube is fantastic btw @PrestonN, had a play with it while testing this change, going to be using it from now on 🙂

**Comment by PrestonN** [comment]
Thank you!  Looks like the implementation works very well, it's much appreciated!  I'll be switching over to your extension now and will likely deprecate the extension that I was supporting.

Feel free to ping me if anyone mentions any issues related to this and FreeTube.  99% of the time the issue's I've seen reported about my extension have been issues about FreeTube itself and not the extension's fault, so I expect a little bit of that to happen here.  I'll keep an eye out and help wherever I can.

Thanks again for implementing FreeTube, it's greatly appreciated! :)

**Comment by SimonBrazell** [comment]
No worries, will do!
