### ISSUE TITLE
Redirect reddit.com to i.reddit.com and/or old.reddit.com.

### ISSUE THREAD

**Issue by btdmaster** [SimonBrazell/privacy-redirect#115]
Yes, I am well aware that both of those are imperfect when it comes to privacy. However, they are a _clear_ improvement over the new interface. Perhaps this could be set as an opt-in?

My personal biased opinion is in favour of https://i.reddit.com (looks to have less tracking and bloat) but https://old.reddit.com is still better than the redesign at https://reddit.com.

But because randomly selecting one seems like a bad decision for everyone, if this is something the devs are interested in adding, I would suggest defaulting to https://i.reddit.com, giving options for https://old.reddit.com. Also, if there is only little interest this feature could be made opt-in rather than opt-out.

**Comment by ToughGuyKunio** [comment]
There's a PR for this: https://github.com/SimonBrazell/privacy-redirect/pull/102

**Comment by SimonBrazell** [comment]
Hi @btdmaster as @ToughGuyKunio mentioned, there is a PR for this already, I need to work out how I want to fit this into the UI before I merge and release this change though. In the middle of moving house atm so no time unfortunately 🙁

**Comment by SimonBrazell** [comment]
I've merged the reddit redirect PR as part of v1.1.43.
