### ISSUE TITLE
Limit read/edit browsing data permissions 

### ISSUE THREAD

**Issue by jwsp1** [SimonBrazell/privacy-redirect#12]
Privacy Redirect asks for read and edit permissions for all websites. This might frighten new users to use your extension since they are worried of being spied out... 
I think this should be limited to the few sites that are listed in README only.

You might want to check out "Recordify Title Discover" extension on Chrome Extension Store (https://chrome.google.com/webstore/detail/recordify-title-discover/kkgbclpocodjecojibeaaglcgndegljl) in order to see that it only asks for limited specific website access. This shows that it would technically be possible.

**Comment by SimonBrazell** [comment]
Hi @jwsp1 this actually was the original setup for this extension, however an increase in permissions was required to allow the redirection of embedded content within iframes, see issue #6.

**Comment by jwsp1** [comment]
Well that's bad news :/ so there's probably nothing to do about it?

**Comment by SimonBrazell** [comment]
No not without breaking embedded invidious videos. 

I think the issue really only affects embedded videos though so perhaps standalone extensions for Nitter and Bibliogram would be a good idea? I already made one for [Nitter](https://github.com/SimonBrazell/nitter-redirect).

**Comment by jwsp1** [comment]
I actually use your extension for YouTube-invidious redirects 😅 but I understand that it's not possible. Thanks for clarification
