### ISSUE TITLE
Can't open youtube links with FreeTube in Firefox

### ISSUE THREAD

**Issue by anyone00** [SimonBrazell/privacy-redirect#123]
Thanks for adding the FreeTube option in Privacy Redirect it is much appreciated, but on one of my machine it does not work:

Firefox give this error:

> The address wasn’t understood
> 
> Firefox doesn’t know how to open this address, because one of the following protocols (http) isn’t associated with any program or is not allowed in this context.
> 
> You might need to install other software to open this address.

Archlinux freetube-git AUR package
Firefox 82.0.2
Privacy Redirect 1.1.42

I've tried removing both Firefox and Privacy Redirect. And recompiling from the AUR package freetube-git and installing them again. but still I get the same error

**Comment by SimonBrazell** [comment]
Hello @anyone00 which URL are you attempting to redirect? I'll try it out on my machine.

**Comment by anyone00** [comment]
I've tried many URL but it still gives me the same error!

So far I've tried:

```
https://youtu.be/aqz-KE-bpKQ
https://www.youtube.com/watch?v=aqz-KE-bpKQ
https://www.youtube-nocookie.com/embed/aqz-KE-bpKQ
https://youtube.com/channel/BlenderFoundation
```

**Comment by SimonBrazell** [comment]
Those links work for me in Firefox and Chrome, perhaps it's a problem with FreeTube itself? 

@PrestonN have you encountered this before?

**Comment by anyone00** [comment]
could it be an archlinux problem or the packaging?

**Comment by anyone00** [comment]
I've used it on ubuntu and there's been no problem

**Comment by SimonBrazell** [comment]
Yeah I'd say this is not likely to be an issue with this extension, I'd open an issue on the [FreeTube repo](https://github.com/FreeTubeApp/FreeTube).

**Comment by anyone00** [comment]
I've tried all AUR packages: 

```
freetube
freetube-git
freetub-bin
```

all have the same issue!

I'll try to contact the maintainer of AUR packages

Thanks!

**Comment by PrestonN** [comment]
Hey there, as @SimonBrazell mentioned, this is not an issue with this extension.

I do not maintain the AUR packages, and can't guarantee that they'll work with a browser extension.  FreeTube needs to be able to register the `freetube://` protocol on your system in order for the browser to know where to send the YouTube link to.  This protocol is not registered with portable versions of FreeTube, which the AUR packages are based on.

For your system, I would recommend either contacting the maintainers to fix this, or by installing the Flatpak version of the application, which does register the protocol properly.  If you have any other issues, please create a new issue over on the FreeTube repository as was suggested.

**Comment by aldobelus0** [comment]
It happens to me as well, in a web browser called Abrowser -a Firefox fork which is used in GNU/Linux free OS like [Trisquel](https://trisquel.info/)- and this extension doesn't work when I try to open a YouTube  link. Of course, both, Abrowser and Privacy Redirect versions are the updated ones.

If I can provide you with more info, just tell me.

**- Edited 31.03.22**
 
My operating system does not depend on AUR. It is a free Ubuntu with packages managed by apt or aptitude. It is the Ubuntu 20.04 LTS version, specifically, called Nabia on Trisquel, version 10.
