### ISSUE TITLE
Why yewtu.be was removed from the list?

### ISSUE THREAD

**Issue by unixfox** [SimonBrazell/privacy-redirect#129]
It seems like it got removed in this commit: b3d6918e337753902109ede2514fbc5aab282b66

**Comment by SimonBrazell** [comment]
Because it doesn't seem to work with embedded videos, console shows the following error when `https://yewtu.be` is set as the instance:

`Refused to display '<URL>' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

Which indicates that the site maintainers have purposely tried to limit iframe / embed usage by setting the above response header.

If you want to continue using it yourself simply set the Invidious instance manually to `https://yewtu.be`. I don't think it should be in the list if it doesn't support all use cases of the plugin, otherwise users will falsely assume the extension is to blame when embeds don't work.

**Comment by unixfox** [comment]
Good catch @SimonBrazell! Can you try again if it works now?

**Comment by SimonBrazell** [comment]
I just tried it, the above error doesn't occur anymore but now it gets stuck on the anti-bot protection, where it counts down for 5 seconds, but instead of redirecting to the video after it just starts the count again.

![Screen Shot 2020-11-14 at 10 51 53 pm](https://user-images.githubusercontent.com/16571951/99146460-861a8180-26cc-11eb-843b-5f3462339456.png)

At first I thought this was because I was using a VPN but it's the same without the VPN also.

**Comment by unixfox** [comment]
Your browser or an extension is probably denying third party cookies. Try without extensions or if you are on Firefox set "cookies" to "cookies from unvisited websites":
![2020-11-14_14-40](https://user-images.githubusercontent.com/4016501/99147164-8c7e0e80-2676-11eb-8e65-48eb2e0b5d5f.png)

You can see on this gif that it works when third party cookies are allowed:
![Peek 2020-11-14 14-37](https://user-images.githubusercontent.com/4016501/99147170-9ef84800-2676-11eb-8a5e-9e06339ce8d9.gif)

Unfortunately I can't do anything against this third party cookies blocking issue for the moment but at least it works out of the box on Firefox and Chrome/Chromium if you don't change any settings related to the cookies. I'm actively working on finding an alternative to the antibot solution.

**Comment by SimonBrazell** [comment]
Yeah makes sense, that's my personal browser so its kinda locked down more than the others I'd typically use for testing.

Hmmm wondering if I should add it back to the list knowing that its not going to work for some people though?

**Comment by unixfox** [comment]
> Yeah makes sense, that's my personal browser so its kinda locked down more than the others I'd typically use for testing.

Don't worry I've got the same setup, it didn't work on mine, so I had to switch to blocking "cookies from unvisited websites". It's not a big deal because my extension "Cookie AutoDelete" delete every 15 seconds the cookies that I don't want.

> Hmmm wondering if I should add it back to the list knowing that its not going to work for some people though?

Well technically on Firefox it is stipulated that it will break some websites, so if it doesn't work for some people then these people know how to solve the issue because they read the warning in the first place.   
I've added a message about this issue on the antibot page so that the user know what to fix in order to have the iframe working properly.

The final decision for adding back the instance is up to you but I think if it works for most of the people then it's safe to add it back. Like I said earlier I'm actively working on removing the antibot with another solution so this issue won't last forever.

**Comment by B0pol** [comment]
> wondering if I should add it back to the list knowing that its not going to work for some people though?

@SimonBrazell that instance that requires to lower browser privacy features (from blocking third-party cookies to unvisited websites), and runs non-free software (the anti-bot protection). Do you really want to add it back?
The people using yewtu.be could add it in extension settings.

**Comment by unixfox** [comment]
> that instance requires to lower browser privacy features to work (if the user has enabled blocking third-party cookies, he need to switch to unvisited websites)

That's a false claim, if the user is using cookie autodelete (like most of the privacy conscious users) this will have the same effect as blocking third-party cookies because in the end the unwanted cookies will be discarded.

Moreover, the setting `switch to unvisited websites` is still a strong privacy setting because the browser will only store third-party cookies from websites that the user deliberately visited by himself.

> and runs non-free software (the anti-bot protection). Do you really want to add it back?

I'm very sorry that the anti-bot protection is a non-free software, unfortunately there is no alternative apart from using Cloudflare but I don't want to use Cloudflare. If you find an alternative that is free software then I'll be pleased to use it instead.

perflyst talked about the anti bot solutions on Invidious instances and according to him: as long as the instance doesn't run a modified version of Invidious and respect the AGPL then they are allowed to be listed in the instances list.

![2020-11-15_11-31](https://user-images.githubusercontent.com/4016501/99181274-62cff080-2725-11eb-8188-5f25e7a2c42f.png)

Link to the source: https://matrix.to/#/!GMIiONJMKtiqFzSxwj:snopyta.org/$15989721283116506qVpuV:matrix.org?via=matrix.org&via=tchncs.de&via=privacytools.io

@SimonBrazell If you agree with B0pol and start to exclude instances that use a program in order to reduce the amount of bots even if it is non-free then please state it in the README and remove the instances that are behind Cloudflare (Cloudflare is a proprietary and non-free software).   
Do note that it will be sad to do that because the working Invidious instances are becoming quite rare nowadays.

**Comment by unixfox** [comment]
A lot have been changed since two days on https://yewtu.be:
- I removed my antibot solution. The iframe should work whatever browser setup you have, whenever you enforce blocking third-party cookies or not.
- 5 process of Invidious are now running at the same time, this should resolve some slow downs that often occurred during the night and make the experience a lot smoother.
