### ISSUE TITLE
Avoid redirecting tweetdeck.twitter.com to nitter

### ISSUE THREAD

**Issue by narFnarF** [SimonBrazell/privacy-redirect#13]
Similar to the other issue #9 regarding studio.youtube.com, the tweetdeck URL should probably not redirect to Nitter.

The faulty URL: https://tweetdeck.twitter.com/

Thanks!

**Comment by SimonBrazell** [comment]
Sorry maybe a silly question (I don't actually use Twitter at all, just read things on it occasionally) what is the tweetdeck URL used for? Is it account specific stuff?

**Comment by SimonBrazell** [comment]
Added to [v1.1.7](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.7), currently pending release on the stores.

**Comment by narFnarF** [comment]
> Sorry maybe a silly question (I don't actually use Twitter at all, just read things on it occasionally) what is the tweetdeck URL used for? Is it account specific stuff?

It's a different website, that allow to log into multiple twitter account at once and see them all in multiple columns on 1 screen and post messages from multiple accounts at once. Its meant to be use by community managers with multiple accounts.

It looks like this: 
https://duckduckgo.com/?q=twitterdeck&t=ffab&atb=v189-1&iax=images&ia=images&iai=https%3A%2F%2Fi.amz.mshcdn.com%2F0THLzrUYgUzK3GmA0X9tjWmHNIs%3D%2Ffit-in%2F1200x9600%2Fhttp%253A%252F%252Fmashable.com%252Fwp-content%252Fuploads%252F2013%252F06%252Ftweetdecknew.jpg

It doesn't play well with Nitter or your extension because it's not mean to be a public view (it requires login to see your multiple accounts). Also, the URL never changes, regardless of what your looking at (it's always tweetdeck.twitter.com and never things like tweetdeck.twitter.com/someUser)

Hope this clarifies it :)

**Comment by SimonBrazell** [comment]
Oh right, yeah thanks, it's implemented now, let me know if there are any problems with it.
