### ISSUE TITLE
FreeTube can't open playlists

### ISSUE THREAD

**Issue by ToughGuyKunio** [SimonBrazell/privacy-redirect#131]
It's not possible to open YouTube playlist URLs with FreeTube. 
I think this is a FreeTube issue so I originally [posted it there](https://github.com/FreeTubeApp/FreeTube/issues/502#issuecomment-725443599). But I'll add it here too so we can keep track of it.

**Comment by SimonBrazell** [comment]
Yes I've noticed this too. 

@PrestonN would this be an issue with the way the extension is redirecting playlist requests or is this an issue with FreeTube itself?

**Comment by PrestonN** [comment]
This is an issue with FreeTube itself.  Our URL parser isn't taking playlist URLs into account properly and needs to be updated.  Once it's updated with FreeTube then it'll work with Privacy Redirect.

Since the issue is logged over on FreeTube, this issue can be closed.

**Comment by SimonBrazell** [comment]
Thanks @PrestonN and @ToughGuyKunio for chasing this up.
