### ISSUE TITLE
Bug: Opening links from users with "tweets" in the name is buggy

### ISSUE THREAD

**Issue by Atrate** [SimonBrazell/privacy-redirect#135]
When using PR to redirect from twitter to nitter.net, opening links when people's usernames have "tweets" in them breaks the redirect. Could also occur for some other keywords.

Example:
https://twitter.com/tweetsauce/status/1331389217688043520?s=20
gets redirected to
https://nitter.netauce/status/1331389217688043520?s=20
which is a broken link.

**Comment by SimonBrazell** [comment]
No problem I'll have a look at this when I next work on the project.
