### ISSUE TITLE
There's now a privacy focused Reddit frontend!

### ISSUE THREAD

**Issue by ToughGuyKunio** [SimonBrazell/privacy-redirect#137]
From about:
> Teddit is a free and open source alternative Reddit front-end focused on privacy. Teddit doesn't require you to have JavaScript enabled in your browser. The source is available on Codeberg at https://codeberg.org/teddit/teddit.
No JavaScript or ads
All requests go through the backend, client never talks to Reddit
Prevents Reddit from tracking your IP or JavaScript fingerprint
Lightweight (teddit frontpage: ~30 HTTP requests with ~270 KB of data downloaded vs. Reddit frontpage: ~190 HTTP requests with ~24 MB)"

This should perhaps be the default for this extension?

URL: https://teddit.net/
Git: https://codeberg.org/teddit/teddit

**Comment by ToughGuyKunio** [comment]
Also I've done some quick testing and it seems to work already with the extension.

**Comment by erotavlasme** [comment]
I agree, it would be useful to have it into privacy redirect.

**Comment by joshbowyer** [comment]
I agree with all of the above. It does handle pictures from i.reddit.com differently, but that looks very simple as well ( i.reddit.com/whyzfg.jpg becomes teddit.net/pics/w:null_whyzfg.jpg )

**Comment by SimonBrazell** [comment]
Great find! I'll definitely add this to the project.

**Comment by grravity** [comment]
Just came to suggest this, glad to hear
