### ISSUE TITLE
feature: list instances

### ISSUE THREAD

**Issue by atomGit** [SimonBrazell/privacy-redirect#14]
might be more user friendly if all known instances for the services could be selected from a drop-down - [Booteille / Invidition · GitLab](https://gitlab.com/Booteille/invidition) does this for Invidious instances if you wanted to look at the code

**Comment by SimonBrazell** [comment]
Hi @atomGit great idea, perhaps a list of recommended instances could be displayed beneath the input when the input is in focus and is narrowed down as the user types, but still allowing manual input if someone has their own instance?

**Comment by SimonBrazell** [comment]
How's this look, just grabbed all the existing instances from each of the repos:

![Screen Shot 2020-02-10 at 5 59 23 pm](https://user-images.githubusercontent.com/16571951/74127578-1eac3e80-4c2f-11ea-9292-12db11d4f259.png)

This solution still allows the user to enter one manually or edit an existing one if they like.

**Comment by atomGit** [comment]
perfect Simon - i think users will appreciate this

**Comment by SimonBrazell** [comment]
Added to [v1.1.7](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.7), currently pending release on the stores.
