### ISSUE TITLE
Add teddit support

### ISSUE THREAD

**Issue by sbstn87** [SimonBrazell/privacy-redirect#142]
As per the ghacks article:
https://www.ghacks.net/2020/12/05/teddit-browse-reddit-in-a-privacy-preserving-way/

"[teddit](https://teddit.net/)  is a web frontend, unlike many others that are available only on mobile devices. You can load the site using any web browser to access Reddit's content.

The core difference between Teddit and Reddit is that the former does not track users and that it has no advertising. In fact, you can load Teddit with JavaScript disabled and it will work just as fine."

**Comment by ToughGuyKunio** [comment]
This is [already fixed](https://github.com/SimonBrazell/privacy-redirect/pull/138) and will be in the next release.

**Comment by SimonBrazell** [comment]
This has now been released in v1.1.44. Cheers!
