### ISSUE TITLE
Unexpected behavior on Reddit redirect to old Reddit

### ISSUE THREAD

**Issue by Svallinn** [SimonBrazell/privacy-redirect#144]
I'm not entirely sure how relevant this is at the moment (given the Teddit and Snew options being added in), but I'll open this anyway.
I'm not entirely sure what's the factor at play in this case, so I'll present my exact case.
In this [reddit page](https://old.reddit.com/r/ArcoLinux/comments/gi8m7y/arco_vs_arch/) (at the time of me writing this), there's a link in the second comment to another reddit page.
If I click that link (and whether the intent is to open on the current tab or another tab), the extension doesn't redirect me to old reddit page.
However, if I copy the link and paste it on the address bar and navigate to it, it does redirect me properly.

Firefox 83.0
Privacy Redirect 1.1.43

**Comment by SimonBrazell** [comment]
Hi @Synkky off the top of my head I'd say this may be caused by a service worker on the reddit page, I've added the teddit and libreddit providers now too if you want to try those instead.

**Comment by SimonBrazell** [comment]
Correct me if I'm wrong but I believe this is no longer an issue with Libreddit now being part of the project?

**Comment by Svallinn** [comment]
You're not wrong
