### ISSUE TITLE
OpenStreetMap redirect breaks Google Earth

### ISSUE THREAD

**Issue by megascrapper** [SimonBrazell/privacy-redirect#146]
When the OpenStreetMap redirect is on, Google Earth fails to load the labels and there are a bunch of error in the console like this:
```
Access to XMLHttpRequest at 'https://openstreetmap.org/#&zoom=17&layers=S' (redirected from 'https://www.google.com/maps/vt/bpb=ChwiGhAFKgoNxOFa2BUAAAAAMgoNAAAAABUA6aQ1ChwiGhAEKgoNSDpOzRUAAAAAMgoNAAAAABUA0klrChwiGhAEKgoNSDpOzRUALraUMgoNAAAAABUAAAAAChwiGhAFKgoNAAAAABUA6aQ1MgoNPB6lJxUA0klrChwiGhAFKgoNAAAAABUAAAAAMgoNPB6lJxUA6aQ1ChwiGhAFKgoNPB6lJxUAAAAAMgoNuMWxMhUA6aQ1ChwiGhAFKgoNAAAAABUAF1vKMgoNPB6lJxUAAAAAChwiGhAFKgoNAAAAABUALraUMgoNPB6lJxUAF1vKChwiGhAFKgoNxOFa2BUAF1vKMgoNAAAAABUAAAAAChwiGhADKgoNSDpOzRUALraUMgoNuMWxMhUA0klrChwiGhAAKgoNSDpOzRUALraUMgoNuMWxMhUA0klrChwiGhABKgoNSDpOzRUALraUMgoNuMWxMhUA0klrChwiGhACKgoNSDpOzRUALraUMgoNuMWxMhUA0klrChwiGhAEKgoNAAAAABUAAAAAMgoNuMWxMhUA0klrChwiGhAFKgoNPB6lJxUAF1vKMgoNuMWxMhUAAAAAChwiGhAEKgoNAAAAABUALraUMgoNuMWxMhUAAAAAEggIABIBbRiYBBoKEgJlbhoCSUQoAyAEWgQIAxAA') from origin 'https://earth.google.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Turning OSM redirect off fixes the issue.

Here's some screenshot for comparison
OSM redirect on:
![](https://i.imgur.com/Tr9fLOZ.png)

OSM redirect off:
![](https://i.imgur.com/6Z5sY0K.png)

Browser: Chrome 87.0.4280.88
OS: Windows 10 2004
Privacy Redirect version: 1.1.43

**Comment by SimonBrazell** [comment]
Yeah can see what you mean, looks like there are JS requests to the `/maps/` path which is caught by the redirect regular expression, I'll see if I can add a rule to ignore if it originates from the `earth.google.com` domain.
