### ISSUE TITLE
Reddit Redirect to Libreddit

### ISSUE THREAD

**Issue by tauin** [SimonBrazell/privacy-redirect#149]
its an alternative frontend for reddit, not many intances though (only https://libreddit.spike.codes and the "official" https://libredd.it/)

EDIT: Repo found [here](https://github.com/spikecodes/libreddit)

**Comment by tauin** [comment]
NVM teddit has been chosen

**Comment by tauin** [comment]
NVM Teddit has been chosen

**Comment by SimonBrazell** [comment]
Now includes both in the latest version.
