### ISSUE TITLE
Libreddit Reddit redirect support

### ISSUE THREAD

**Issue by opusforlife2** [SimonBrazell/privacy-redirect#151]
Hi. There is another Reddit frontend which is based on the Reddit redesign, unlike Teddit which is based on Old Reddit.

https://github.com/spikecodes/libreddit

Another user opened an issue to request this but closed it on their own. I'm putting this here for you to consider.

**Comment by spikecodes** [comment]
Hi, I'm the author of Libreddit, thank you for sharing it! Yeah I think it would be a great addition to Privacy Redirect along with Teddit.

**Comment by somoso** [comment]
I've made a PR here for this to be added: https://github.com/SimonBrazell/privacy-redirect/pull/153

**Comment by SimonBrazell** [comment]
@somoso, @opusforlife2 PR merged, lookout for v1.1.44, thanks for the suggestion, and for introducing me to Libreddit, will certainly be using it myself!

@spikecodes great work!
