### ISSUE TITLE
No option to install with browser Vivaldi

### ISSUE THREAD

**Issue by i300220** [SimonBrazell/privacy-redirect#152]
There is no option to install your extension with Vivaldi latest on Win 7 sp1 64.  
All we see is an info page.

<a href="https://ibb.co/rbmsDZL"><img src="https://i.ibb.co/M8s6FRj/Clipboard01.jpg" alt="Clipboard01" border="0"></a>

It installed correctly on Vivaldi latest debian buster.

**Comment by i300220** [comment]
More info.

To have it to install in Vivaldi, I had do load the extension as unpacked, but before I had to remove stuff from manifest:
Hope that helps.

`@ -66,10 +66,10 @@
  "options_ui": {
    "page": "pages/options/options.html",
    "open_in_tab": false
  },
  }/*,
  "browser_specific_settings": {
    "gecko": {
      "id": "{b7f9d2cd-d772-4302-8c3f-eb941af36f76}"
    }
  }
  }*/
}`

**Comment by SimonBrazell** [comment]
Hi @i300220 haven't tried it on Vivaldi, can you normally install other extensions direct from the chrome web store?

**Comment by i300220** [comment]
> Hi @i300220 haven't tried it on Vivaldi, can you normally install other extensions direct from the chrome web store?

Hi Simon,

Used to.  Now recently, all my chrome extensions were installed on my win 7 64 laptop in  _all_  chromium browsers, vivaldi included.  I even was able to upgrade opera and vivaldi to the latest version yesterday and all extensions are still there and working.

On my win 7 64 desktop though,  lastpass is not instaling as well even though it has   been working   well for years. I've opened a ticket with them.  All in all,  chrome extensions from chrome web store  used to install on my desktop. It's not the cas anymore.  It seems particular to that machine.

**Comment by SimonBrazell** [comment]
Not sure how I could troubleshoot it then, I don't have a Win7 install around. Sounds more like an issue with Vivaldi, have you tried searching the issues on their repo?

**Comment by SimonBrazell** [comment]
Looks like it should be supported - [https://help.vivaldi.com/desktop/appearance-customization/extensions/](https://help.vivaldi.com/desktop/appearance-customization/extensions/)

**Comment by i300220** [comment]
Thanks for the info Simon.  When Lastpass refused to install, I get very suspicious and reinstalled Vivaldi from scratch, reinstalled extensions, and imported bookmarks.  All is fine now.  Something somehow has become corrupted.  There is nothing a fresh reinstall could take care of.

**Comment by SimonBrazell** [comment]
Good to hear, all the best!
