### ISSUE TITLE
Invidious doesn't work with FreeTube for me

### ISSUE THREAD

**Issue by tiotrom** [SimonBrazell/privacy-redirect#154]
I get this error regardless of the instance used:
![image](https://user-images.githubusercontent.com/34804533/103964079-d78a3e80-515a-11eb-9105-48ed80d64c3e.png)

Using Firefox.

**Comment by ChocoTonic** [comment]
it's because invidious doesn't work when the `&autoplay=0` is in the URL and the `invidious.snopyta.org` instance I'm on does not like that

hopefully a fix comes out where when you uncheck the "Invidious automatically play video on load" it doesn't put `&autoplay=0` there

![image](https://user-images.githubusercontent.com/41702116/104028241-57c19b80-517d-11eb-9b1a-5b104fbfb4ea.png)

hopefully this gets fixed ASAP

**Comment by tiotrom** [comment]
I have that option unchecked, and it is still not working...

**Comment by SimonBrazell** [comment]
I can't reproduce this, working fine for me on Firefox and Chromium, just working on a new build now so I can fix it if you can give me more details.

**Comment by tiotrom** [comment]
Yes it was my mistake. I had enabled "open in freetube" and that's why the links didn't work. Apparently the freetube option does not work...

**Comment by SimonBrazell** [comment]
@tiotrom it should work, I use it all the time.

@ChocoTonic what issue are you referring to? I just tried redirects with `autoplay` on and off and didn't have any issues, apart from it not autoplaying... has this option been deprecated?

**Comment by tiotrom** [comment]
I cannot make it open in FreeTube in Linux. Clicking any youtube link, simply opens up in invidious. Am I doing something wrong? :)

**Comment by SimonBrazell** [comment]
I'm not sure Freetube supports all Linux distros, I vaguely remember this coming up in the past. I'd check the Freetube repo.

**Comment by SimonBrazell** [comment]
#123 might be relevant?

**Comment by tiotrom** [comment]
> I'm not sure Freetube supports all Linux distros, I vaguely remember this coming up in the past. I'd check the Freetube repo.

Well I have freetube installed on my system, so it surely works. But Firefox cannot find a program on my system to open the youtube links with, so it fails. That's what I understand

Let me know if I can debug it somehow that may help you figure it out ;)

**Comment by SimonBrazell** [comment]
Sorry @tiotrom but I don't support FreeTube, please post on their repo if you're having issues with it in your environment. The privacy redirect side of things is very simple, it just redirects the request to `freetube://` if there is no app listening for that scheme on your OS then it won't work, privacy redirect has nothing to do with this.

**Comment by SimonBrazell** [comment]
See [this comment](https://github.com/SimonBrazell/privacy-redirect/issues/123#issuecomment-723654220) from one of the maintainers.

**Comment by tiotrom** [comment]
Ah ok yes that answers the question since I have installed it via AUR. Thanks a lot for the clarification. I'll close this now.
