### ISSUE TITLE
Silently enabling new switches due to updates is bad

### ISSUE THREAD

**Issue by cloudrac3r** [SimonBrazell/privacy-redirect#160]
Being sent to random searx instances when I typed `!g` into duckduckgo was extremely confusing to me. It took me more than 5 minutes to work out that it was Privacy Redirect's fault. The same thing happened when reddit alternatives were added. This isn't fun.

When you add a new switch, existing users need to be notified about that in some way. Here's some options for you to consider:

- Open a tab with notes of new services when the extension updates. (Downsides: Intrusive.)
- Enable the switch silently, but the first time (first 2 times, 3 times, or always until dismissed?) the new redirect is activated, the user can see a notice in the page informing them of what happened and providing an easy way to turn it off and go back.
- Disable the switch by default, and have a notice in the page that informs the user that there's a new option available from PR, and allow them to enable it right there.
- Disable the switch by default, and leave them to discover for themselves that it exists. (Downsides: Difficult to discover.)

Personally I'm a fan of option 3.

Thoughts?

**Comment by SimonBrazell** [comment]
Hi @cloudrac3r 

Sorry to put you through that. 

> Disable the switch by default, and have a notice in the page that informs the user that there's a new option available from PR, and allow them to enable it right there.

I agree with you, this method seems like the best approach. When you say "notice in the page" do you mean something like a "NEW!" tag next to the toggle switch in the popup and settings page or something else?

**Comment by SimonBrazell** [comment]
Also wondering if it's worth disabling it in a new release now that it's already out in the wild...

**Comment by gsitreble2019** [comment]
Please disable it. Especially when search engine is changed without info, it seemed to me like some terrible virus or worm got inside my computer.


(Thanks for your great work!

**Comment by SimonBrazell** [comment]
Okay so I'm disabling the search engine redirects if the `disableSearchEngine` is undefined on update / install and I've added the following to the settings and popup:

<img width="302" alt="Screen Shot 2021-01-12 at 21 24 05" src="https://user-images.githubusercontent.com/16571951/104302141-8a241d80-551c-11eb-9258-9d54d1babd0d.png">


<img width="412" alt="Screen Shot 2021-01-12 at 21 21 12" src="https://user-images.githubusercontent.com/16571951/104301862-3d404700-551c-11eb-821a-c1956a44e057.png">

Do you think I should do the same to the Reddit redirects while I'm at it?

**Comment by cloudrac3r** [comment]
> When you say "notice in the page" do you mean something like

The NEW badge is good too, but what I actually meant that you could insert an element into the google website, and other websites in the future, to tell people about the option existing. This way it's discoverable even if people don't open the extension view.

![image](https://user-images.githubusercontent.com/28467304/104401819-d5d8d480-55b9-11eb-8ce8-2e22c23b1886.png)

"Don't show again" would make it not show again for in this case google. Every time you add a new category there would be a prompt the first time the user navigates to that.

> Do you think I should do the same to the Reddit redirects while I'm at it?

The rEddit redirects are fine being on by default now. They just caught me off guard the first time it happened. Which is the problem that I'm trying to solve for the future - not being caught off guard by silent changes.

**Comment by SimonBrazell** [comment]
Oh yeah that seems like a nice feature, I was planning to add a new tab changelog on update to alert users to this sort of thing but as you mention perhaps that's a little invasive. Perhaps I could combine the two and have a little popup like this on update which asks the user if they want to read the changelog instead. Either way I won't automatically switch on new features like this in future so it should be less of a problem going forward.
