### ISSUE TITLE
Libredd.it short links are not redirected correctly

### ISSUE THREAD

**Issue by M86xKC** [SimonBrazell/privacy-redirect#165]
When opening a [redd.it link](https://redd.it/kpocos) it redirect to the [wrong libredd.it](https://libredd.it/comments/kpocos) page (Which gives a _Error: Nothing here_ page)

Instead it should just replace the redd.it with libredd.it: https://libredd.it/kpocos (without adding /comments in path)

**Comment by SimonBrazell** [comment]
Should be fixed in the next release, 1.1.47, due on the stores shortly.
