### ISSUE TITLE
duckduckgo

### ISSUE THREAD

**Issue by i300220** [SimonBrazell/privacy-redirect#167]
Hi,

First thanks to this extraordinary extension.

I use duckduckgo as my search engine so I whitelisted it for not being redirected to crap like Bing or worst.  Search engine redirect is set off.

However duckduckgo can use tags e.g. !g to redirect to google search or !imdb to redirect to imdb.  That is what I wanted to keep intact, hence the whitelisting of duckduckgo.

Side effect, and that is the problem I want to report here, Clicking youtube links inside the duckduckgo results page or using the !yt tag goes indeed to youtube since it's been whitelisted.

I don't know if it's at all possible to do or implement, but that would be a very appreciated feature.

Thanks!

**Comment by SimonBrazell** [comment]
Hello @i300220 you shouldn't need to create an exception for DuckDuckGo, the exception feature is only for sites that would normally be redirected by the extension, DDG isn't normally redirected even with the search engine redirects enabled.

**Comment by i300220** [comment]
Right,  many thanks.  I appreciate it!
