### ISSUE TITLE
Intercept outbound links from services other than Invidious

### ISSUE THREAD

**Issue by opusforlife2** [SimonBrazell/privacy-redirect#168]
When redirects are on for a service, Privacy Redirect should intercept outbound links to the original service even when already on an instance of its alternative. For example Old Reddit links on Libreddit should be intercepted so that the user isn't accidentally taken to the old.reddit.com domain.

Services to investigate:
- Nitter
- Bibliogram
- Reddit alts
- OSM
- Search engine alts

We aren't looking to implement this for Invidious because the "Watch on YouTube" link would keep redirecting the user back to Invidious.

**Comment by SimonBrazell** [comment]
The problem here is that these services all have a links to the original service (e.g. "Watch on YouTube" for Invidious) on each page, so there is code specifically written to handle this, disabling redirects if the request originates from say Libreddit or Invidious.

I'm not sure how to give users the best of both worlds here.

**Comment by opusforlife2** [comment]
I'm mostly clueless about web programming, but is it possible to use certain attributes of the anchor tags?

For example, Invidious has `title="Watch on YouTube" ` inside the anchor tag meant to take the user to the original link on Youtube, and a `<i class="icon ion-logo-youtube"></i>` tag nested inside it.

Maybe the other services have similar identifiers that mark the specific links meant to open in the original websites?

**Comment by SimonBrazell** [comment]
> is it possible to use certain attributes of the anchor tags?

When a request is intercepted by the extension it receives only minimal information about where the request came from, only the following details are passed through:

```
{
    "frameId": 0,
    "initiator": "https://duckduckgo.com",
    "method": "GET",
    "parentFrameId": -1,
    "requestId": "3579",
    "tabId": 79,
    "timeStamp": 1618726300713.249,
    "type": "main_frame",
    "url": "https://www.youtube.com/watch?v=_tJ5DA8YY18"
}
```

As you can see there is no reference to the original element (e.g. anchor tag) in these details so it wouldn't be possible to filter on any attributes contained on the anchor tag.

**Comment by opusforlife2** [comment]
Another option is to have a button in the right click menu like uBlock Origin and other extensions have. A button that lets you open a certain link on the original service. The normal clicks on all services can be set to redirect to the chosen private alternative instance.

Here I'm assuming that opening a link to original service will be a rare event. Because if you as user find yourself opening the original service all the time... just use the original service, no?

Is this something workable?
