### ISSUE TITLE
support for other youtube addresses

### ISSUE THREAD

**Issue by rezad1393** [SimonBrazell/privacy-redirect#17]
can this addon support the other youtube addresses like https://youtu.be and other shortcuts for it.

**Comment by SimonBrazell** [comment]
Hello @rezad1393 it should work with YouTube.be addresses, do you have a specific one you're trying?

**Comment by SimonBrazell** [comment]
No you're right it doesn't match that domain, I'll fix it up now.

**Comment by SimonBrazell** [comment]
Let me know if you come across any others.

Cheers!

**Comment by SimonBrazell** [comment]
I've deployed a new build (v1.1.14) which should address this issue, pending release on [AMO](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/) and [Chrome Web Store](https://chrome.google.com/webstore/detail/privacy-redirect/pmcmeagblkinmogikoikkdjiligflglb). let me know if there are still any problem.
