### ISSUE TITLE
Clicking difficulty

### ISSUE THREAD

**Issue by Mennaruuk** [SimonBrazell/privacy-redirect#173]
I've been having trouble with selecting Invidious instances. It seems as if the addon isn't registering my clicks sometimes. The same issue can be encountered in every dropdown list. I reproduced this on two computers.

https://user-images.githubusercontent.com/52135169/106372459-d903ec80-633d-11eb-9c82-bd57b969e1d8.mp4

**Comment by SimonBrazell** [comment]
Hi @Mennaruuk so this is an intermittent issue, as in it only occurs sometimes or is it all the time for you?

What browser and OS are you running?

**Comment by Mennaruuk** [comment]
Happens every time I try to change to another instance. I reproduced this on Windows 10, Manjaro, and Linux Mint. This happens on Firefox and Brave, and most likely other browsers. This is on Linux Mint on Brave, for example:

https://user-images.githubusercontent.com/52135169/107442966-e8392600-6b05-11eb-9af2-0166795a8ff7.mp4

**Comment by SimonBrazell** [comment]
Strange, it doesn't happen for me, I just tried using Chromium and Firefox, it worked every time, that's on macOS, I'll try later on with Windows 10 and Ubuntu.

**Comment by Mennaruuk** [comment]
I'm thinking this has to do with the text. When I click on the text region of any of these boxes, it's less likely to be chosen. When I click on the non-text regions, they are 100% chosen. See what I mean below:

https://user-images.githubusercontent.com/52135169/107443432-d2783080-6b06-11eb-9b26-879224132719.mp4

**Comment by SimonBrazell** [comment]
Ah yes I can see what you mean now, it's when you click the text that is already in the input that the drop down stops working, just reproduced it on my machine. So should be able to fix it now.

**Comment by Mennaruuk** [comment]
Thank you @SimonBrazell !

**Comment by SimonBrazell** [comment]
No worries thanks for letting me know about this.
