### ISSUE TITLE
Don't redirect other libreddit / teddit instances

### ISSUE THREAD

**Issue by B0pol** [SimonBrazell/privacy-redirect#174]
Currently, all instances will redirect to libredd.it (default) or the instance set in settings.
As with Invidious, nitter, Bibliogram, it should not do this.
It should be optional (I think there is an issue for this, #168, but i'm not sure)

There is old.reddit.com in the list, as well as i.reddit.com, I don't know what to do about them. I would like them still be redirected but that would not make sense with this option. 
Why are they in the instances list? I think they should be removed and people still wanting this redirection should add them manually (BTW that's what they have to do currently, except it's suggested when searching reddit.com)

**Comment by SimonBrazell** [comment]
@B0pol are you asking for there to be an instance pool instead? That's something I want to add, I'll likely remove all the other alternatives if I do this and just go with Libreddit I think, it works well and is in line with the ideas behind this extension.

**Comment by frostrenew** [comment]
Maybe all other isntances selectable in settings should be added to Exceptions, behind the scenes? However, it should be toggle-able or else could be considered malicious.

**Comment by TROMsite** [comment]
Teddit is a great reddit option. It is mature and provides RSS feeds. Just saying...

**Comment by SimonBrazell** [comment]
@B0pol is this the behaviour you are describing - https://github.com/SimonBrazell/privacy-redirect/issues/168#issuecomment-820870232

**Comment by B0pol** [comment]
It is fixed using master branch, I'm now waiting for the release :)
