### ISSUE TITLE
Add redirect for Google Search

### ISSUE THREAD

**Issue by The-Mer0vingian** [SimonBrazell/privacy-redirect#18]
Hello, can you add auto redirect from Google to DuckDuckGo?

**Comment by SimonBrazell** [comment]
Hi @The-Mer0vingian yes I was considering adding this feature, there is actually another issue open at the moment requesting the same thing but using Searx instead, so whichever solution I do add I'll try make it search engine agnostic.

**Comment by SimonBrazell** [comment]
Closing this in favour of #16
