### ISSUE TITLE
Reddit redirects

### ISSUE THREAD

**Issue by obeho** [SimonBrazell/privacy-redirect#180]
The instances for reddit alternatives are growing rapidly, so instead of keeping up with lag, please add Libreddit under Advanced tab in options for the extension.

I wanted to make `libreddit.himiko.cloud` my default instance but it wasn't listed in the extension.

**Comment by SimonBrazell** [comment]
@obeho you can add your own custom instance to the instance input, so can use whatever site you like, the drop down is just some suggested known instances.

**Comment by obeho** [comment]
Sorry, dont know how to do that for reddit.

**Comment by SimonBrazell** [comment]
Sorry for the delay, been busy with other stuff lately.

1. Click the extension icon in the top right of your browser to bring up the popup window (where you can enable/disable redirects)
2. Click "More options", where you should be taken to a new window containing the extension's extended options.
3. On the "General" tab scroll down to "Reddit Instance" and click on the input.
4. You will see the list of available instances appear below the input.
5. Here you can either select one of the predefined instances or enter your own into the input using the keyboard. 

**Note -** make sure you include the protocol with the instance domain, e.g. **`https://`**, so you should enter `https://libreddit.himiko.cloud` (note, no trailing `/` also) into the input, you should be able to do this for all other instances too, setting them to whatever you like even if it's not one of the predefined ones.
