### ISSUE TITLE
Redirection to Freetube only opens the app

### ISSUE THREAD

**Issue by ElishaDaugherty** [SimonBrazell/privacy-redirect#185]
The redirect only works partially. Only the freetube app is opened, without being redirected to the video from which the extension redirected.

Firefox: 85.0.2
Privacy Redirect: 1.1.46
Freetube: 0.11.2

**Comment by paulverbeke** [comment]
I'm experiencing the same behavior on my end.

Firefox: 87.0
Privacy Redirect: 1.1.46
Freetube: 0.12.0

**Comment by ElishaDaugherty** [comment]
If you use freetube from the AUR, then this bug has already been fixed. It seems that the .desktop file was ignoring the url that was delivered, because the %U variable was missing.
Everything is correct on the privacy-redirect side. Sorry! ❤️
