### ISSUE TITLE
Please do not add &local=true to every invidious url

### ISSUE THREAD

**Issue by 94b42c29dd** [SimonBrazell/privacy-redirect#19]
While this makes more videos work, it puts a lot of strain on the invidious instances. Every video will be pulled from the invidious instance instead of pulling it from Google's severs. If a lot of people do it, it will be infeasible for many instances to function correctly (or at all) because the demand of bandwidth will be incredibly high. It will affect the user negatively in the end.

**Comment by SimonBrazell** [comment]
Perhaps if I was to make this an 'Advanced Option' instead, not set by default, putting the option in the settings page and not in the popup window?

**Comment by 94b42c29dd** [comment]
Sure i don't think that would be a problem.

**Comment by SimonBrazell** [comment]
This has been implemented in [v1.1.15](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.15).
