### ISSUE TITLE
Reddit search doesn't redirect (anymore?)

### ISSUE THREAD

**Issue by Jonta** [SimonBrazell/privacy-redirect#196]
**Describe the bug**
Reddit-search does not redirect to libreddit-search

**To reproduce**

1. https://www.reddit.com/search?q=cat redirects to
2. https://libredd.it/search/

**Expected behavior**
https://libredd.it/search/?q=cat&sort=relevance&t=all

Firefox, Privacy redirect 1.1.46

Mentioned here: https://github.com/spikecodes/libreddit/issues/140

**Comment by spikecodes** [comment]
Thanks for this bug report! The issue was specific to Libreddit but has been fixed in https://github.com/spikecodes/libreddit/issues/140#issuecomment-787151064.
