### ISSUE TITLE
Add the possibility to configure custom Nitter and Invidious instances.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [SimonBrazell/privacy-redirect#2]
Making the extension redirect to other instances of [Nitter](https://github.com/zedeus/nitter/wiki/Instances) and [Invidious](https://github.com/omarroth/invidious/wiki/Invidious-Instances) should be pretty easy to do, as you only really need to replace the nitter and invidious instance name by the one chosen by the user.
However, a setting extension page for it still need to be done.

**Comment by SimonBrazell** [comment]
This is a great idea, I'll look into adding it.

**Comment by SimonBrazell** [comment]
Was actually thinking of adding a menu to allow the user to disable the redirects if they like too.

**Comment by SimonBrazell** [comment]
Do you think this should be a list of predefined instances or a text field for entering whatever instance they want?

**Comment by PoorPocketsMcNewHold** [comment]
Well, I think predefined Instances should be better. It may cause some issues when some instances dissapears or when the list isn´t updated, but it shouldn´t change that heavily to be honest.

**Comment by SimonBrazell** [comment]
I'll make it a text field for now that way the user can add whichever instance they like and we don't have to a maintain a list in the extension.

**Comment by SimonBrazell** [comment]
Finally got around to doing this, pushed up to the stores, let me know what you think.

**Comment by moppman** [comment]
Great work!
Unfortunately, the twitter redirection doesn't work at all for me in Firefox 69.0.1

**Comment by SimonBrazell** [comment]
@moppman, that's strange, wonder if there is anything I can do to stop this behavior in the future, might need to read up on the Firefox API a bit more. Thanks for the update and workaround!
