### ISSUE TITLE
Visiting youtube-dl.org redirects to invidious

### ISSUE THREAD

**Issue by ToughGuyKunio** [SimonBrazell/privacy-redirect#20]
Found this bug in latest version: Visiting https://youtube-dl.org/ redirects to invidious.

**Comment by SimonBrazell** [comment]
Thanks @ToughGuyKunio I'll look at fixing this and some other things mentioned here in the next release. Been busy with some other projects lately so haven't had much time available but I'll short this out as soon as I can. Cheers!

**Comment by SimonBrazell** [comment]
Found a bit of time! This should be fixed now in [v1.1.15](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.15).
