### ISSUE TITLE
nitter instance - weaponizedhumiliation.com no longer exists

### ISSUE THREAD

**Issue by grrrrr** [SimonBrazell/privacy-redirect#207]
nitter.weaponizedhumiliation.com is no longer a valid nitter instance,  the domain now redirects to a namecheap parking page.  It would be useful to have this removed from the default instances

**Comment by palaeodendrologist** [comment]
You can manually remove it from the settings panel, the list will always update with extension

**Comment by grrrrr** [comment]
> You can manually remove it from the settings panel

Yes, I've done that, but it does not help those who have not,  they will still get random failures until it is removed from the rotation

**Comment by alefvanoon** [comment]
#216 done.

**Comment by SimonBrazell** [comment]
Thanks everyone, @alefvanoon's change should be included in v1.1.47.
