### ISSUE TITLE
Incorrectly redirect pwnyoutube.com

### ISSUE THREAD

**Issue by narFnarF** [SimonBrazell/privacy-redirect#21]
Hi again!

I found another incorrect redirection.

When trying to access `pwnyoutube.com` it redirects to invidious. I think it should not redirect and allow access to pwnyoutube normally.

For info, `pwnyoutube.com` is a useful way to access http://deturl.com which provides various tools and services that use youtube videos.

**Comment by SimonBrazell** [comment]
Thanks @narFnarF I'll fix this up in the next build.

**Comment by SimonBrazell** [comment]
Should be fixed in [v1.1.16](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.16).
