### ISSUE TITLE
Add our instances

### ISSUE THREAD

**Issue by TROMsite** [SimonBrazell/privacy-redirect#217]
We are using and testing our instances daily and we try to make sure they work. For some, like invidious, it is bloody difficult. But hey, they work:

https://insta.trom.tf - bibliogram
https://ytb.trom.tf - invidious
https://search.trom.tf - searx
https://bird.trom.tf - nitter

**Comment by alefvanoon** [comment]
thanks for your great work!
I did them check #216 
Except https://ytb.trom.tf.
it's not working!

**Comment by TROMsite** [comment]
https://ytb.trom.tf. is working for all individual videos. Not working to search and see channels unfortunately. Waiting for an update that will fix these. And thanks!

**Comment by SimonBrazell** [comment]
Thanks @alefvanoon and @TROMsite much appreciated.
