### ISSUE TITLE
Redirect Mobile Links

### ISSUE THREAD

**Issue by grravity** [SimonBrazell/privacy-redirect#22]
Mobile links don't seem to redirect, at least in Twitter's case, I haven't tested the other sites.
For example, mobile.twitter doesn't redirect to nitter, but twitter redirects to nitter no issues as expected.

**Comment by SimonBrazell** [comment]
Thanks @grravity I'll look into it, so it's just `mobile.twitter...` links that aren't redirecting?

**Comment by grravity** [comment]
Again, haven't checked all the links for all the platforms, but I can confirm mobile.twitter was having issues

**Comment by SimonBrazell** [comment]
Should be fixed in [v1.1.16](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.16).

**Comment by SimonBrazell** [comment]
@grravity I just released a [new version](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.17) that proactively removes the Twitter service worker as I discovered it was interrupting some Nitter redirects, this may have been the cause of your issue, please re-test and let me know if it is still occurring.

Cheers!

**Comment by SimonBrazell** [comment]
Closing this for now as I haven't heard from you, if you are still experiencing this issue please let me know and I'll re-open / investigate further.

Cheers!

**Comment by grravity** [comment]
Oh my bad I missed it, it seems to be working good now!

**Comment by SimonBrazell** [comment]
Oh great! Good to hear. 

I'd still like to add your other suggestion to this extension, just not had much time lately to look into it.

**Comment by grravity** [comment]
Am on your latest, but curiously did you mess with something with the actual re-direction for embeds? 
If I choose not to whitelist cy.tube, I don't even see Invidious show-up in uMatrix, nor is it loading the video in cy.tube.

Just curious about this, I know the point was to whitelist cy.tube and use YouTube not Invidious, but I wasn't sure why it's doing this as I recall it still grabbing and playing the Invidious videos just not as stable as using YouTube. Now it's not even grabbing the Invidious video (and yes I removed Cy.tube from the whitelist and refreshed, so it's not like it's whitelisted currently).
