### ISSUE TITLE
Support for Piped

### ISSUE THREAD

**Issue by FireMasterK** [SimonBrazell/privacy-redirect#220]
Hey, I'd like to add Piped as a youtube alternative frontend.

https://piped.kavin.rocks/

https://github.com/TeamPiped/Piped

Let me know what I can do to get started!

Would I add this just like a regular Invidious instance? Or would something else need to be done.

Thanks again!

**Comment by moriel5** [comment]
Related (though happily, not a duplicate of) issue #181.

I'm just another user here, however I can already tell you from what I had read, that Piped is built differently than Invidious, not only in frontend, but also in backend (NewPipe-Extractor).

**Comment by FireMasterK** [comment]
Closing as this is a duplicate of #181.
