### ISSUE TITLE
youtu.be redirection not working fully

### ISSUE THREAD

**Issue by p-rintz** [SimonBrazell/privacy-redirect#221]
Hi there,

the youtu.be redirection seems to lead to the actual video part of the url being dropped.

So for example: https://youtu.be/xZQ6hshnuOU will be redirected to https://invidio.us without the video part attached to the end, leading to the video (obviously) not being played.

Please dont hesitate to ask if you need further information.

**Comment by moriel5** [comment]
I wonder if this is similar to issue #183, in that it is an issue with upstream?

**Comment by SimonBrazell** [comment]
What instance are you using? `invidio.us` doesn't exist anymore.

**Comment by SimonBrazell** [comment]
> https://youtu.be/xZQ6hshnuOU

Works fine for me, it loads "Build Guide: [Immune and Tanky: CI Soulrend/Bane Occultist]" on invidious.snopyta.org

**Comment by p-rintz** [comment]
It's a private instance. 

It works fine for normal YouTube.com links. (And with other extensions that do only invidious redirection)

I'll try to test some more scenarios and post when I know more.

**Comment by SimonBrazell** [comment]
No worries.

**Comment by p-rintz** [comment]
Some more information/Another question:
The redirection does happen and it also appends the string to the end of the invidious instance url, but it doesnt do it with the "watch=" string. This makes the invidious instance ignore it and simply show the homepage.

ie: https://youtu.be/xZQ6hshnuOU
gets redirected to: https://invidio.us/xZQ6hshnuOU instead of https://invidio.us/watch?v=xZQ6hshnuOU

Is this expected? Maybe its something I need to fix in my nginx reverse proxy configuration?

**Comment by petterreinholdtsen** [comment]
I still experience this problem, when redirecting to yewtu.be, with Privacy Redirect version 1.1.49 on Firefox.

**Comment by petterreinholdtsen** [comment]
I just discovered a fix for this issue is pending in https://github.com/SimonBrazell/privacy-redirect/pull/425 .
