### ISSUE TITLE
Common settings for reddit instances

### ISSUE THREAD

**Issue by notthewave** [SimonBrazell/privacy-redirect#223]
e.g. 
`https://SOMEREDDITINSTANCE/r/programming+privacy` **Self defined subreddits**
instead of
`https://libredd.it` **r/all or r/popular**

This works across instances.

**Comment by SimonBrazell** [comment]
Hi @notthewave, please correct me if I'm wrong but this sounds more like a feature request for the [Libreddit project](https://github.com/spikecodes/libreddit)?

**Comment by notthewave** [comment]
This feature is already implemented by reddit itself hence it also works on teddit and libreddit.
I thought it would be nice to have some common settings that are applied across instances like with invidious in the advanced panel. 

But it's probably best to have it implemented upstream first... 

Common settings are not a bad idea however... 
But for that it's best for for something like proposed in #174 to be implemented first.

Will change the title.

**Comment by SimonBrazell** [comment]
I'm not sure I follow, can you give me some examples including actual URLs of what you are after?

Sounds to me like this is something associated with your reddit account settings and if so then this behaviour should be replicated on libreddit, etc.

**Comment by notthewave** [comment]
Nope. You can display a summary of multiple subs via `+` in the URL path.
`https://SOMEREDDITINSTANCE/r/SOMESUBREDDIT+ANOTHERSUBREDDIT+SUBREDDIT3`

**Here are a few examples:**
Summary of programming, privacy, firefox and github on a teddit instance:
https://teddit.ggc-project.de/r/programming+privacy+firefox+github
Summary of blender, freecad, cgi and cad on a libreddit instance
https://libredd.it/r/blender+freecad+cgi+cad
Summary of rust, cprogramming, java, lua and python on old.reddit
https://old.reddit/r/rust+cprogramming+java+lua+python

**Comment by notthewave** [comment]
It is now possible in libreddit and teddit to subscribe to Subreddits via some cookie functionality, I believe. Maybe it is possible to use this feature across instances along with nsfw toggle or other settings.
