### ISSUE TITLE
bibliogram.kavin.rocks is a rick roll

### ISSUE THREAD

**Issue by eitan-j** [SimonBrazell/privacy-redirect#233]
bibliogram.kavin.rocks redirects to youtube.com/watch?v=dQw4w9WgXcQ. Other kavin.rocks sites (nitter.kavin.rocks, libreddit.kavin.rocks, etc.) seem to be working normally. kavin.rocks itself is also a rick roll, but according to [the internet archive](https://web.archive.org/web/20200701000000*/kavin.rocks), this has been the case since at least November 2020.

**Comment by xanoni** [comment]
Overall I noticed that 100% of the Bibliogram instances I tried were at least partially blocked by Instagram, so very little of the content loads. Does this mean Instagram has won the battle? Would disable the Bibliogram feature by default, because this is frustrating.

**Comment by fattalion** [comment]
> Does this mean Instagram has won the battle?

You could think of it like that, but I imagine the situation would be much better with non-public instances.
