### ISSUE TITLE
Invidious instance redirect without avanced settings

### ISSUE THREAD

**Issue by TikiThorsen** [SimonBrazell/privacy-redirect#237]
Hello, lately I started using the Invidious Instance "https://inv.riverside.rocks" (which is working surprisingly good). Created an account, imported subscriptions and customized the settings.

I want to use only the redirect option in PR without the settings in "Invidious/Advanced".
Example: local=true&quality=dash&dark_mode=true&volume=100&autoplay=1

Is there any way to disable that part of the redirect?

**Comment by austinhuang0131** [comment]
If your setting is as follows then you can remove all query strings, **except** `autoplay`:

![Screen Shot 2021-05-16 at 11 41 56](https://user-images.githubusercontent.com/16656689/118403285-c9ce5380-b63b-11eb-8838-58c721b0d560.png)

**Comment by L1pE** [comment]
How does one reset the volume setting so it doesn't apply? I can't seem to figure it out.
