### ISSUE TITLE
Libredd.it and teddit.net redirect me to old.reddit

### ISSUE THREAD

**Issue by pitsi** [SimonBrazell/privacy-redirect#238]
I have been using privacy redirect for ~3 months now and mainly for redirecting reddit to old.reddit and istagram to bibliogram. The first days I was also using it to redirect twitter to nitter.net, but a couple of weeks later I was getting the "this instance has been rate limited, use another instance instead", so I disabled that redirection.

A couple of days ago I noticed that tha addon redirects me to old.reddit for both libredd.it and teddit.net. Disabling it allows me to visit those 2 sites normally. In general, I do not notice performance issues on most of the subreddits under old.reddit, but a couple of them feel as sluggish as in the regular reddit, thus the need to visit them under libredd.it or teddit.net.

Debian testing/unstable x64, brave 1.24.85, privacy redirect 1.1.47.

**Comment by SimonBrazell** [comment]
Hmm yeah that sounds annoying, not sure why it would be doing that, must be something up with how the reddit redirects are implemented. I'll look into it!
