### ISSUE TITLE
Youtube video player broken on cs50.harvard.edu

### ISSUE THREAD

**Issue by Latrolage** [SimonBrazell/privacy-redirect#247]
Not sure if this is because of the specific way they implemented youtube onto the site or if this is a problem fixable on this end, or invidious' but the extension breaks the video player at https://cs50.harvard.edu/college/2021/spring/weeks/0/

**Comment by SimonBrazell** [comment]
Yeah seems a bit strange, looks like an iframe within an iframe, I'd say it's most likely something specific to how the embeds are implemented on that site. I'd just use an exception for that page instead.
