### ISSUE TITLE
Firefox: scrollbars in popup

### ISSUE THREAD

**Issue by ToughGuyKunio** [SimonBrazell/privacy-redirect#25]
Very minor cosmetic "issue" but in Firefox there are unnecessary scrollbars in the popup settings. In Brave/Chrome there are none.

**Comment by SimonBrazell** [comment]
Hi @ToughGuyKunio, I haven't experienced this myself, would you mind posting a screenshot, which OS are you running?

**Comment by ToughGuyKunio** [comment]
![privacyredirectscrollsbars](https://user-images.githubusercontent.com/12818876/77141333-6915ac00-6a74-11ea-9567-4554b219e7a0.png)

OS: Manjaro Linux
Browser: Firefox 74.0

I tested Firefox Developer Edition and there are scrollbars there too.

**Comment by SimonBrazell** [comment]
No probs, I'll see if I can get rid of this in the next build.

**Comment by SimonBrazell** [comment]
Should be fixed in [v1.1.16](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.16).

**Comment by ToughGuyKunio** [comment]
That seemed to fix it.

**Comment by SimonBrazell** [comment]
Cheers!
