### ISSUE TITLE
ban kavin.rocks

### ISSUE THREAD

**Issue by 9738ga** [SimonBrazell/privacy-redirect#253]
https://invidious.kavin.rocks redirects requests to https://www.youtube.com/watch?v=dQw4w9WgXcQ

It might also be worthwhile to remove nitter.net from the list, since it has not been working for months.

Edit: I seem to have put the link wrong, also at the time of editing this has no troll behavior, for now.

**Comment by Elaborendum** [comment]
I thought it was removed in #234 ?

**Comment by 9738ga** [comment]
> I thought it was removed in #234 ?

Oh, sorry, I surely forgot to remove the closed issues filter when searching.

I see that a solution was merged some time ago and that there have been recent updates to the firefox addon. 
However in both my firefox profile and a newly created one I have that troll server.

**Comment by thebiblelover7** [comment]
@9738ga you should probably close this issue.

**Comment by 9738ga** [comment]
@thebiblelover7 It is still valid, perhaps you have not read the last phrase of my previous message. I have checked it again in a new profile and the problem persists.

**Comment by comradekingu** [comment]
@ghost Both the kavin.rocks instance and nitter are up now.
