### ISSUE TITLE
Redirect direct links to images and videos on twitter

### ISSUE THREAD

**Issue by Kezxo** [SimonBrazell/privacy-redirect#26]
If you open a link that leads to video.twimg.com or pbs.twimg.com the extension should redirect them to nitter.

To get examples just check the direct links to images or videos on any nitter tweet.

**Comment by SimonBrazell** [comment]
Yes agreed, I've actually added these two hosts to the Twitter redirects in the build I'm currently working on, so it should be in the next release.

**Comment by SimonBrazell** [comment]
Should be fixed in [v1.1.16](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.16).
