### ISSUE TITLE
Ability To Whitelist Sites

### ISSUE THREAD

**Issue by grravity** [SimonBrazell/privacy-redirect#27]
Would like to request the ability to whitelist websites from redirecting, this is beneficial on sites that have trouble with Invidious in embeds and you don't mind them passing through, but want other sites to continue using the redirection.

One site in specific I find I have issues is cytube.
https://cytu.be/

**Comment by SimonBrazell** [comment]
This is a great idea, actually something I've had suggested before, it's a little more work to add than some of the stuff I'm planning for the next release, but certainly something I plan to include in the near future.

**Comment by SimonBrazell** [comment]
Looking at doing this now, wondering to what extent I should go to on this... I could for instance add it as a UI to the popup menu, allowing users to simply add the current site to the whitelist, which sounds ideal but means I need to add an [extra permission](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs) to the extension, which I'm sure not everyone will be pleased about.

With this in mind perhaps it's a better idea to go with a more simple approach and make the user manually enter the address they want to exclude from the redirects, via copy and paste from the browser or typing it in if they prefer. How does that sound?

**Comment by grravity** [comment]
>With this in mind perhaps it's a better idea to go with a more simple approach and make the user manually enter the address they want to exclude from the redirects, via copy and paste from the browser or typing it in if they prefer.

Yeah I'm +1 for this, it's not a difficult thing to do. If you add wildcard support that'd be great so we can choose to whitelist a specific URL or an entire domain for example.

**Comment by SimonBrazell** [comment]
> Most people probably won't even have to touch this feature tbh.

Good point, I might place this feature in the options menu for now I think, save cluttering up the popup menu.

> If you add wildcard support that'd be great so we can choose to whitelist a specific URL or an entire domain for example.

Yep, I was thinking the same, I can include support for the user to enter Regular expressions perhaps?

> I'd honestly say incorporate a custom forwarder as well.

Could be done relatively easily with the current level of permissions, might not add it this time around, but a good idea for the future!

**Comment by SimonBrazell** [comment]
[v1.1.22](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v.1.1.22) includes this feature, might be a little rough, tested it using your use case though (https://cytu.be/) and it works

**Comment by grravity** [comment]
Glad to hear, thank you so much!

**Comment by SimonBrazell** [comment]
Hmm better try v1.1.23 instead, I made a mistake with the last that broke some redirects.

**Comment by grravity** [comment]
I made a reply, I guess it didn't go through. Sorry if you get double I'll delete one if I see it went through.

But essentially I asked if you messed with embeds at all, as I notice if I don't add cytu.be to the whitelist (yes I get the point of the issue was to implement the whitelist and use YouTube instead of Invidious), it doesn't even seem to fetch from Invidious anymore. I recall it fetched the video from Invidious previously when I originally opened this issue, and it was able to play it, it was just kinda funky. Now though it doesn't seem to be even grabbing Invidious as it's not showing up in uMatrix or showing anything on the site (with YouTube blocked through uMatrix).

And yes I'm on your latest.

**Comment by SimonBrazell** [comment]
I modified all the redirects to first check if the site the request originated from (initiator) is in the whitelist, if it is then there is no redirect regardless of the source (iframe, etc.).

I'm not sure I follow, it's breaking embeds is it?

**Comment by SimonBrazell** [comment]
Can you try a different Invidious instance? I've noticed today that the default instance is down or really slow, but https://invidious.snopyta.org seems to be working.

**Comment by grravity** [comment]
I have Snopyta's instance set as my redirect, and yeah so If I click a YouTube link it redirects to the Invidious instance no issues.

But in cytube, it's not loading Invidious embeds (again, no cytube isn't currently whitelisted). It's only loading YouTube/GoogleVideo according to uMatrix.

I'm not sure if it's an issue with emebds or something else If you have a site that has a lot of emebds on it I can see.

**Comment by SimonBrazell** [comment]
Hmm yeah perhaps there is another problem then, I normally verify embeds using https://www.reddit.com/r/videos/ which is loading correctly for me now using v1.1.23.

**Comment by SimonBrazell** [comment]
Also just confirmed the embeds on https://cytu.be again, first with it in the whitelist, which loaded embedded video from youtube, then with it not in the whitelist, which loaded the player from Invidious.

**Comment by grravity** [comment]
> 
> 
> Also just confirmed the embeds on https://cytu.be again, first with it in the whitelist, which loaded embedded video from youtube, then with it not in the whitelist, which loaded the player from Invidious.

Sorry, late response haven't had time lately to fuck with this.
Ok, I got it. So, with cytube It's loading the Invidious embed and playing the video.

But playing around with it, it seems to be having trouble actually syncing the video to cytube. So cytube essentially is supposed to sync the time with everyone watching, so if the video is playing at 2:00/10:00 everyone should be at 2:00. With your redirect enabled it doesn't sync to that time, it just starts the video from the beginning it seems. This could be an Invidious issue, I'm not sure. Not sure how I'd test that. 
Was wondering if you knew or could try to fix, as that should essentially make cytube  fully functional then.
And yes, I know it's your  add-on (or at least Invidious) that is the issue because I disabled the Invidious Redirects temporarily, then refreshed and it seemed to sync fine with YouTube player.

**Comment by SimonBrazell** [comment]
Perhaps the plugin is still interfering with the youtube assets some how, maybe I can catch it by looking at what's going on in the console.

**Comment by SimonBrazell** [comment]
Just looking at this now, it seems to be in sync to me, I've got two windows open, one with the plugin using the whitelist and the other without, they both seem to be in sync.

I had a look at the console too and I can see a lot of errors but they seem to be unrelated. 

So yeah as far as I can see the whitelist is working?

**Comment by grravity** [comment]
Not the whitelist.
Just want to ensure I'm clear on the issue:

Basically if I open cytu.be on Firefox, then open on Chromium, Firefox has the Privacy Redirect extension (Chromium doesn't), if I add a video into cytu.be using the YouTube URL, it appears and starts playing on both Chromium and Firefox (on Firefox it redirects through the Invidious embed as expected and as it should **without the whitelist on**). 
Now if I wait say a minute into the video, and refresh the page on Firefox, it starts the video back to 0:00 on Firefox (and obviously continues on Chromium no issue). 
Now as Chromium is continuing, and Firefox is playing from 0:00, if I disable the "Invidious Redirect" option in your privacy redirect extension on Firefox, and refresh the page, it starts playing through YouTube as expected.. but, when playing through YouTube it IS in sync with the chromium browser now (it jumped up to 4:00 or wherever the Chromium instance is at, unlike it did when Firefox was redirecting the embed through Invidious).
I don't think it has anything to do with my [Firefox user.js](https://raw.githubusercontent.com/grravity/firefox-config/master/user.js) or anything as when I disable the Invidious redirect in your extension it works no issues, which makes me think it's either your extension or Invidious. But I could be wrong.

Again, this is all with the whitelist **disabled**, just running through Invidious.
I know this kinda "defeated the purpose" of implementing the whitelist, but sometimes Invidious does have slowdowns depending on your instance, and YouTube would be more coherent. But I know not everyone would want to whitelist YouTube IF Invidious can work, the Whitelist is nice to have if Invidious can't work.
Invidious IS working in this situation, it's just having trouble with syncing. Again, not sure if this is an Invidious issue or a cytu.be issue (I'm using Snopyta's Invidious instance if that helps for more granular troubleshooting). But either Invidious isn't working properly with sync, or your extension/embeds implementation is having trouble with sync. It would be very nice to be able to use Invidious through cytu.be though in sync if possible. If you still do not find any issues after my explanation,

**Comment by SimonBrazell** [comment]
Oh right sorry I think I understand now, I'd say that the issue there lies with Invidious and its lack of support for whatever YouTube interface this particular site is using to sync and resume the videos. 

Not sure there is anything that can be done about that, I'll have a play around with it but I'd say that its unlikely to be something easily fixed.
