### ISSUE TITLE
[Enhancement] Embed instagram content

### ISSUE THREAD

**Issue by stemy2** [SimonBrazell/privacy-redirect#28]
Hello,

Invidious redirection can embed videos, but bibliogram redirect can't, so instead of embedded images, we have this:
![Screenshot_20200327_081723](https://user-images.githubusercontent.com/22192600/77731748-6c241580-6ffb-11ea-8351-424639e7aab3.png)

**Comment by SimonBrazell** [comment]
Hi @stemy2 , I'm not sure I follow what you are after here, so you have come across some embedded instagram content? If so can you post a link to it, I can use it for testing whatever solution we come up with here.

**Comment by SimonBrazell** [comment]
@stemy2 I've only just been made aware of this, I will fix this up this week, instagram embeds will be bypassed for now and sent on to Instagram.
