### ISSUE TITLE
Redirect to Lilo Search

### ISSUE THREAD

**Issue by thenotilus** [SimonBrazell/privacy-redirect#315]
Lilo is a French search engine.

Search Url : https://search.lilo.org/?q={serchTerms}
Open Search : https://search.lilo.org/opensearch.xml
Website : https://www.lilo.org

**Comment by thenotilus** [comment]
> This search engine seems to be geofenced. I get "Sorry, our search engine is not available at this time in your country." when I try to search for something.

Oh damn, which country are you in ?

**Comment by MegaCoom** [comment]
I'm not sure tbh. I'm using Tor and I tried it multiple times without success. So either Lilo only allows a small number of countries or it blocks Tor users, which I would consider a very questionable practice for a privacy oriented search engine.
