### ISSUE TITLE
Redirect Google to startpage

### ISSUE THREAD

**Issue by boriskieffer** [SimonBrazell/privacy-redirect#32]
Hello,
You can redirect Google to startpage.com, since startpage.com is a proxy between Google and the user.
Results are practically the same, except the fact that startpage.com doesn't store anything about user in order to provide a better search.

https://support.startpage.com/index.php?/Knowledgebase/Article/View/184/22/why-do-i-get-different-results-with-startpagecom-than-google

**Comment by SimonBrazell** [comment]
Hi @boriskieffer thanks for the suggestion, I am planning to add a feature that allows search engine redirects at some point, which will allow users to select whichever search engine they prefer, including StartPage. 

I'm going to close this in favour of #16 which I'll leave open to track this feature.

Cheers!
