### ISSUE TITLE
Don't rewrite requests on the Instagram reserved URL list

### ISSUE THREAD

**Issue by cloudrac3r** [SimonBrazell/privacy-redirect#33]
Hi, developer of Bibliogram here!

For a couple of months now my Bibliogram request logs have contained listings for rather strange URLs, and I've finally figured out what's causing them — your extension. There's a few things to explain here, so I'll start at the start to make sure we're all on the same page. There's a summary at the bottom of this page if you're really cool and already know everything I'm about to say.

Usernames on Instagram are on the top level, for example, `instagram.com/radionewzealand`. The username here is `radionewzealand`. This puts them on the same level as other Instagram pages which are _not_ usernames, like `/explore`, `/accounts`, `/graphql`, and `/embeds.js`. Therefore, if we see a URL like `/privacy`, we don't know if we'll visit Instagram's privacy page, or someone with the username `privacy`.

On Bibliogram I decided that I didn't want to deal with this problem, since I of course would like to have my own paths like `/imageproxy` without having to worry if there is a person on Instagram with the username `imageproxy` whose profile would then become inaccessible. So, I put all users onto the path `/u/{username}`, so that any person on Instagram can be visited without me having to worry. Posts are still on `/p/`, and I expect that when I implement the explore feature it will be on `/explore/` too.

However, people making redirect extensions like yours do actually have to deal with this confusion when deciding whether or not to rewrite a request on instagram.com. It would be rather bad if someone was POSTing their login credentials to Instagram to try to log in there, but some extension rewrote this and sent them to a random person's Bibliogram instance.

Thus, to try to help extension authors, I have written this reference of all of Instagram's reserved URLs that I've found so far (there may be more that I don't know about). https://github.com/cloudrac3r/bibliogram/wiki/Reserved-URLs

Here are the actual strange requests I've received that I spoke about at the start, that you need to not rewrite, however there are very likely more that are currently being rewritten that I just haven't noticed yet:

- `/embed.js` (ww­w.instagram.com) has been rewritten to `/u/embed.js` (Bibliogram)
- `/en_US/embeds.js` (platform.instagram.com) has been rewritten to `/u/en_US/embeds.js` (Bibliogram)
- `/accounts/confirm_email/redacted/redacted` (domain unknown) has been rewritten to `/u/accounts/confirm_email/redacted/redacted` (Bibliogram). Yes, really. The text `redacted` used to be a base64 string that was probably private data, but I decided not to examine it. I don't know if it was a GET or POST.

As part of this, I noticed that you were redirecting the secondary request to platform.instagram.com/en_US/embeds.js to Bibliogram. This is a script that is required on another site to display Instagram's post embeds — [see here for one example](https://mashable.com/article/who-did-instagram-egg-world-record/). platform.instagram.com is reserved for their tracking and embedding code to be run on 3rd-party websites. It's probably best that you don't rewrite requests on this domain at all, unless you really want random instance owners to be able to XSS any website with an Instagram embed. Bibliogram does not support external embeds at the moment, and it's not a high priority feature, but I can let you know in the future if you should change this behaviour.

Somewhat related, l[ooking at the code,](https://github.com/SimonBrazell/privacy-redirect/blob/4d02035847206d8dfc52bf2c52956ae9ebae0c07/background.js#L24) I see you have some sort of expression to match `/imageproxy`, `/u`, and `/static`. These look like Bibliogram endpoints. Can you explain what this does and why it's necessary?

**Summary**

- Add a better filter of requests to not rewrite, perhaps using [the list on the Bibliogram wiki](https://github.com/cloudrac3r/bibliogram/wiki/Reserved-URLs) as a base.
- Consider not rewriting things on the domain platform.instagram.com, or things loaded as 3rd-party scripts.
- Bibliogram has no embeds feature, but I can let you know if this changes.

**Comment by SimonBrazell** [comment]
Hi @cloudrac3r thanks for the very detailed feedback and creating Bibliogram! 

I'm sorry this extension has caused you grief, I'll do my best to sort these issues out as soon as I can. When I added support for Bibliogram to this extension it was on advice from one of the extension's users, they didn't give me much info to go on, so I basically just did it by trial and error, so I'm not surprised there are mistakes. Sorry for not reaching out for more information, I'll endeavour to be more communicative in the future, it's actually something I should do for all the services this extension makes use of...

The regex you linked to is a list of 'reserved paths' that aren't redirected as users, I can do something similar for the reserved paths mentioned in your wiki. I'm wondering where I should redirect those that aren't implemented on Bibliogram though? Is there any appropriate page on Bibliogram for these redirects? 

Apologies again for the grief this issue may have caused, I'll try to get this fixed up this week some time.

**Comment by cloudrac3r** [comment]
No problem.

> I'm wondering where I should redirect those that aren't implemented on Bibliogram though?

Your choice. For things like embed.js and /accounts, I'd suggest not rewriting at all, and just letting the request go to Instagram. For things like /explore and /directory, you could either not rewrite, or you could send the user to a 404 page on Bibliogram. I can make a custom "this feature is not implemented" page if that helps. It's your choice in the end.

Why are paths from Bibliogram in the reserved paths regex? Could you explain to me how this works/why this is necessary?

Don't be afraid to ask if you have more questions/comments!

**Comment by SimonBrazell** [comment]
> Your choice.

I'm easy, for now I'll just redirect them to the 404 page, but if you fo include a "this feature is not implemented" page at some point I will use that instead.

> Why are paths from Bibliogram in the reserved paths regex? Could you explain to me how this works/why this is necessary?

Some of them probably aren't necessary, I'll have a closer look at this when I fix this all up.

> Don't be afraid to ask if you have more questions/comments!

Thank you! I will likely take you up on this 😀

**Comment by cloudrac3r** [comment]
Oh, please note that there is only ever one path element for profiles — /yyy could be a user page, but /yyy/zzz is definitely not. So I suggest not rewriting anything that has more than one path element.

**Comment by SimonBrazell** [comment]
> Oh, please note that there is only ever one path element for profiles

Okay thanks, I'll include a check for this in the redirect also.

**Comment by SimonBrazell** [comment]
Hi @cloudrac3r , pretty sure I've got a solution to this problem but I thought I should run it by you first:

- Only requests coming from the `main_frame` (a document that is loaded for a top-level frame), are redirected, so nothing coming from an iframe or script which should stop the extension breaking embeds as they are not currently implemented by Bibliogram anyway.
- `instagram.com`, `www.instagram.com`, `help.instagram.com`, `about.instagram.com` only these domains are redirected to Bibliogram (`platform.instagram.com` not included).
- `/p`, `/developer`, `/legal`, `/about`, `/explore`, `/support`, `/press`, `/api`, `/privacy`, `/safety`, `/admin`, `/help`, `/terms`, `/contact`, `/blog`, `/igtv` these reserved paths are redirected to Bibliogram, where the user will be either met with a 404 if they are not available or some content if there is something implemented for them.
- `/accounts`, `/embeds.js`, `/embed.js` these paths will not be redirected to Bibliogram.

Let me know if there are any issues.

Cheers!

**Comment by cloudrac3r** [comment]
Sounds perfect!

**Comment by SimonBrazell** [comment]
Cool I'll fix up the other issue you reported this afternoon and do a new build that includes the changes.

**Comment by SimonBrazell** [comment]
Those changes should all be implemented in [v1.1.21](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.21)
