### ISSUE TITLE
Add brave Search

### ISSUE THREAD

**Issue by ghost** [SimonBrazell/privacy-redirect#338]
Can you add Brave Search in the list of search engine redirection.

**Comment by craftyguy** [comment]
please no.

**Comment by silverwings15** [comment]
please no

**Comment by ghost** [comment]
why not give choice are you so childish that you don't want to let choice to other ?
Free and opensource mean liberty of choice too ...

**Comment by craftyguy** [comment]
> Free and opensource mean liberty of choice too ...


No, it does not: https://www.gnu.org/philosophy/free-sw.en.html

**Comment by ghost** [comment]
> > Free and opensource mean liberty of choice too ...
> 
> No, it does not: https://www.gnu.org/philosophy/free-sw.en.html

LMAO, Free as free speech, it mean liberty .... seem i have over estimated the capacity of some user to be intelligent

**Comment by ghost** [comment]
Please no. Brave Search is not an example of privacy.

**Comment by ghost** [comment]
> Please no. Brave Search is not an example of privacy.

proof ?

**Comment by ghost** [comment]
To start with, as sson as Brave Search is opened, before anything else, Brave fills the user's localStorage with :

```
usageMetrics.metric_activity
usageMetrics.installts
usageMetrics.metric_activity_home
usageMetrics.version
usageMetrics.channel
```

Which is not a perfect example of privacy. You don't do that. A habit nowadays to fill the localStorage (or even the indxedDB!) with what could/should perfectly well be handled by cookies. It is often the practice of sites which are aware of the fact the user may delete cookies but omit his localStorage.
Not good. I block cookies for this site, so no data is layed. I very occasionally visit this search engine but -- apart from privacy -- a one page only of web results is laughable. Image and video search is quite good on the other hand, hence why I don't totally avoid the place.

**Comment by ghost** [comment]
> To start with, as sson as Brave Search is opened, before anything else, Brave fills the user's localStorage with :
> 
> ```
> usageMetrics.metric_activity
> usageMetrics.installts
> usageMetrics.metric_activity_home
> usageMetrics.version
> usageMetrics.channel
> ```
> 
> Which is not a perfect example of privacy. You don't do that. A habit nowadays to fill the localStorage (or even the indxedDB!) with what could/should perfectly well be handled by cookies. It is often the practice of sites which are aware of the fact the user may delete cookies but omit his localStorage. Not good. I block cookies for this site, so no data is layed. I very occasionally visit this search engine but -- apart from privacy -- a one page only of web results is laughable. Image and video search is quite good on the other hand, hence why I don't totally avoid the place.

It happen often to you to check you local storage even before checking the web settings or even read their parametter ?

Disable metrics generate : 
app.usageMetricsOptOut : true

After that only : usageMetrics.version
and : usageMetrics.installts

Are used (both simple int).
Note do not know if it's delete old one but it not add new so if it bug you manually delete the old one.

So YES they are privacy friendly

**Comment by ghost** [comment]
1- Metrics should be opt-in, not opt-out
2- If you set the option to opt-out, the user's choice is kept ... in his localStorage, not in a cookie, which means that if the user wipes Firefox data on exit, even if he has chosen to keep the brave cookie, his choice for metrics will be wiped out as well.

A healthy place does not proceed this way. I could give examples of sites which did poceed as above-mentioned (localStorage instead of cookie(s) and which have abandonned that practice later on, i.e. Qwant Search which now handles all options in cookies.

I don't want to bash Brave Search and even less Brave as a whole; I'm only pointing out a fact which is not in the policy of sites deliberately motivated by privacy concerns.

**Comment by ghost** [comment]
> 1- Metrics should be opt-in, not opt-out 2- If you set the option to opt-out, the user's choice is kept ... in his localStorage, not in a cookie, which means that if the user wipes Firefox data on exit, even if he has chosen to keep the brave cookie, his choice for metrics will be wiped out as well.
> 
> A healthy place does not proceed this way. I could give examples of sites which did poceed as above-mentioned (localStorage instead of cookie(s) and which have abandonned that practice later on, i.e. Qwant Search which now handles all options in cookies.
> 
> I don't want to bash Brave Search and even less Brave as a whole; I'm only pointing out a fact which is not in the policy of sites deliberately motivated by privacy concerns.

I can say the same for firefox, but even firefox don't do it.

So the choice must be held in the user hand and not our !!
You replicate what Microsoft & Google do "we know what's is good for you we don't care of your choice".

FOSS is choice !!!!!

for transparency i actually use brave browser with duckduckgo as search engine.
