### ISSUE TITLE
Google Maps consent page

### ISSUE THREAD

**Issue by mooreye** [SimonBrazell/privacy-redirect#353]
If you go to
https://maps.google.com/
it shows consent.google.com instead of redirecting to OSM.

**Comment by ThomasDNguyen** [comment]
@mooreye Can you provide the settings or check again to see if it still shows consent.google.com? I just tested your link and it brings me directly to OSM.

**Comment by mooreye** [comment]
> @mooreye Can you provide the settings or check again to see if it still shows consent.google.com? I just tested your link and it brings me directly to OSM.

Yes now it works, I don't know what happened but certainly it didn't work earlier.

**Comment by Fxsch** [comment]
Someone should close this issue

**Comment by mooreye** [comment]
> Someone should close this issue
