### ISSUE TITLE
SimplyTranslate instance

### ISSUE THREAD

**Issue by Clone5030** [SimonBrazell/privacy-redirect#355]
The old site (translate.metalune.xyz) is deprecated and it redirects to simplytranslate.org, there isn't a choice to change the site in the extension. Pls fix it, thanks!

**Comment by ThomasDNguyen** [comment]
@jendeukieee You can simply select the whole text (ctrl + a) and paste the new link in [as such](https://i.imgur.com/AH6UFOn.png) (yes, it can be any link). This works for all of the links and instances btw. I think a better UI design is to list the original website we'd like to redirect and then the available libre and privacy respecting alternatives (like how they do it over at [libredirect](https://libredirect.github.io/)). That way the UI doesn't trick the users into thinking the only way is to choose from the drop-down menus.

**Comment by Clone5030** [comment]
Oh wait, you could type in that box?? Never knew, thanks so much!
