### ISSUE TITLE
Invidious URL parameters disappear + dark theme

### ISSUE THREAD

**Issue by jones137** [SimonBrazell/privacy-redirect#36]
Unfortunately, Invidious seems to forget its URL parameters when navigating within it. To reproduce:

- go to youtube.com -> it redirects to invidio.us with 'local' and 'quality' parameters
- click on INVIDIOUS in the top left: it loads the main page again, but URL parameters are not there anymore. Same if you go to a video, channel etc.

So, not only YouTube links need to be redirected, but Invidious's own as well.

While at it, it would also be very convenient to add an option to load dark theme (parameter for that is 'dark_mode=true'). Nitter has it by default, but majority of Invidious instances do not unfortunately.

**Comment by SimonBrazell** [comment]
Hi @jones137 thanks for the info, I'll see if there is a way to persist these flags, preferably without having to redirect Invidious to Invidious as well. 

> While at it, it would also be very convenient to add an option to load dark theme

No worries, will do.

Cheers!

**Comment by SimonBrazell** [comment]
Added both these suggestions just now, please try `v1.1.25` on [AMO](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/)

You'll need to go to options and then enable `Persist Invidious preferences (as cookie)` in the `Advanced` tab before it will persist your settings for you, you'll notice the dark mode option there too. 🙂

**Comment by SimonBrazell** [comment]
This feature works by utilising the existing Invidious preferences cookie, so you'll need to enable cookies for it to work, let me know if there are any issues.
