### ISSUE TITLE
Don't redirect for twitter homepage feed?

### ISSUE THREAD

**Issue by leethax666** [SimonBrazell/privacy-redirect#38]
I love the idea of using nitter for individual tweets but it keeps redirecting my main feed link to nitter and it doesn't support it.

**Comment by SimonBrazell** [comment]
Hi @leethax666 I could add a few exceptions to the redirect rules that would stop these specific pages from being redirected?

Are you able to provide a list of pages that you don't want redirected? Or is it not that simple?

I'm actually working on adding a 'whitelist' feature to the extension at present which could also help here too perhaps.

**Comment by tarbib** [comment]
Exactly what I am looking for Twitter too. Like it would only redirect if there is something after the "/" of "twitter.com/" so that I can still have access to my twitter timeline without disabling your addon.

**Comment by SimonBrazell** [comment]
Yep happy to add this feature, just wanted some help identifying the paths to exclude from the redirects as I don't use Twitter accounts myself normally.

**Comment by tarbib** [comment]
@SimonBrazell Nice ! Sorry Actually the URL to exclude is "https://twitter.com/home".

**Comment by SimonBrazell** [comment]
Should be implemented in v1.1.33, let me know if there are any issues.

**Comment by tux93** [comment]
For me twitter.com/home is still redirected, even if it is explicitly added to the Whitelist

**Comment by SimonBrazell** [comment]
It worked in my testing last night... Must have made a mistake before pushing live.

**Comment by SimonBrazell** [comment]
Okay I think I published the wrong extension bundle last night, sorry I'll fix this up now, `web-ext build --overwrite-dest` got me! 🙂

**Comment by tarbib** [comment]
@SimonBrazell it's working for me! thank you :)
Side remark : I would have thought that from twitter.com/home, doing a right-click on a tweet time, opening in a new tab would convert the tweet link to nitter but it's not.

**Comment by tux93** [comment]
I can confirm the behaviour @tarbib describes on Firefox, on Chromium links opened form the Home timeline are redirected to Nitter, but on Chromium there's a different issue: it tries to load assets like pictures through Nitter which fails due to Twitters Content Security Policy, here's an example from the dev tools console:

```
Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' blob: data: <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL>".
home:1 Refused to load the image 'https://nitter.nixnet.services/pic/https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1177915712695869440%2FhqapR7rU_normal.jpg' because it violates the following Content Security Policy directive: "img-src 'self' blob: data: https://*.cdn.twitter.com https://ton.twitter.com https://*.twimg.com https://www.google-analytics.com https://www.periscope.tv https://www.pscp.tv https://media.riffsy.com https://*.giphy.com https://*.pscp.tv".
```

**Comment by SimonBrazell** [comment]
@tarbib the reason for that is due to the way I had to implement this, basically the extension excludes any requests made for a Twitter domain where the `initiator` site is either the selected Nitter instance or a Twitter domain. So trying to navigate from a Twitter domain to another will fall into this category.

@tux93 it seems that the implementation of the `initiator`  varies between browsers, this plus the additional script included in the extension to remove the Twitter service worker is making this feature very hard to implement... 🙁

**Comment by SimonBrazell** [comment]
@tux93 can you tell me what version of Chromium you're running?

**Comment by SimonBrazell** [comment]
Sounds pretty recent so that's not it. I can see what you mean on Chromium, I can't even login as the extension seems to be redirecting some background scripts which prevents me submitting the login form.

**Comment by siutsin** [comment]
> @tarbib the reason for that is due to the way I had to implement this, basically the extension excludes any requests made for a Twitter domain where the `initiator` site is either the selected Nitter instance or a Twitter domain. So trying to navigate from a Twitter domain to another will fall into this category.
> 

@SimonBrazell great feature. Is it possible to have an option only to redirect if the regex is matching?
