### ISSUE TITLE
[Feature request] Please add support for imdb.com redirects to libremdb.herokuapp.com

### ISSUE THREAD

**Issue by onchov** [SimonBrazell/privacy-redirect#385]
As per the title. Thanks.

**Comment by theRoboxx** [comment]
Hi there,
I believe this repo is no longer maintained.
You should have a look at the fork https://github.com/libredirect/libredirect.

They also implemented the redirect to libremdb.herokuapp.com!

**Comment by onchov** [comment]
Closing as per the above comment.

**Comment by onchov** [comment]
Closing as per the above comment.
