### ISSUE TITLE
Cannot navigate back in the browser after being redirected

### ISSUE THREAD

**Issue by Innoxious** [SimonBrazell/privacy-redirect#39]
As per title. I am on Firefox with extension version number 1.1.21

**Comment by SimonBrazell** [comment]
Hi @Innoxious I can't seem to be able to reproduce this, are you able to provide a URL that exhibits this behaviour that I can use to test?

My basic test just now was using [https://old.reddit.com/r/videos/](https://old.reddit.com/r/videos/) where I selected the first YT video that appeared, which redirected to Invidious as expected. I then navigated back, which took me back to [https://old.reddit.com/r/videos/](https://old.reddit.com/r/videos/), as expected.

**Comment by Innoxious** [comment]
Ahh sorry @SimonBrazell. I figured out the issue. I am running the Facebook Container extension and the Google Container extension, so the container was triggering first, and then the redirect.

**Comment by SimonBrazell** [comment]
All good, hope you were able to resolve it.
