### ISSUE TITLE
Could you please create two separate extensions

### ISSUE THREAD

**Issue by treble2019** [SimonBrazell/privacy-redirect#4]
Would be nice to have 2 separate extensions one for nitter and one for invidio.us. Mainly because we have lots of issues with youtube very slow/not loading sometimes from  invidio.us.

Thanks

**Comment by SimonBrazell** [comment]
Hi @treble2019, I've made one for Nitter already, you can find it [here](https://github.com/SimonBrazell/nitter-redirect). But if you are having issues with slow load times for invidio.us you could try one of the other [instances](https://github.com/omarroth/invidious/wiki/Invidious-Instances) to see if they are faster for you. 

Are you running the latest version of this extension from the stores? It allows you to switch off Nitter or Invidious redirects individually and configure different instances.

**Comment by SimonBrazell** [comment]
Haven't heard from you so I'm closing this for now, let me know if you still have an issue.
