### ISSUE TITLE
Website Links not redirecting all links

### ISSUE THREAD

**Issue by WandeingLagomorph793** [SimonBrazell/privacy-redirect#40]
If I save a youtube link via bookmark or input a channel via the id, it redirects just fine.

But if I open it through reddit or go through via a search engine like DDG, it still takes me to regular Youtube instead of Invidious, It didn't use to do this but now it does. I've seen the same thing on Twitter and it might happen with sites like Instagram too
Way to reproduce it is

https://duckduckgo.com/?t=ffab&q=rain+music&ia=videos
Search a video like this one, click any of the youtube links, either below or in the videos tab
It'll redirect to Youtube

Save it as a bookmark and opening that same video from there
Redirects to Invidious.

Same steps for Twitter too, these all used to redirect no matter what but now it's only with some links, depending on how their accessed.

This is with the default invidio.us domain and with all the default settings, same with Nitter and everything else, these worked before but now only work sometimes.

**Comment by SimonBrazell** [comment]
Hi @WandeingLagomorph793 thanks for letting me know, it sounds like I've made a mistake with the latest build, I'll work on a fix now.

**Comment by SimonBrazell** [comment]
Please try the latest release - [v1.1.23](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.23), should be up on AMO now.
