### ISSUE TITLE
Remove wikiless?

### ISSUE THREAD

**Issue by f478ccf2** [SimonBrazell/privacy-redirect#409]
I mean, the main outlines of this project is:
1. No JavaScript or ads.
2. All requests go through the backend, client never talks to Wikipedia.
3. Prevents Wikipedia getting your IP address.
4. Self-hostable. Anyone can setup a private or public instance.

1 - Wikipedia works completely fine without JavaScript, and since when did Wikipedia have ads?
2 - I don't see the problem here. This applies to every website, use a VPN (self host with Algo if you want)
3 - I still don't see the problem. All websites see your IP address, use a VPN
4 - What benefit does this give?

How is Wikipedia different from any site on the internet? I understand websites like Twitter and Reddit having self hosted front-ends (because they're laden with trackers, unnecessary JavaScript, and are quite slow), but Wikipedia? What makes Wikipedia so special to need its own private frontend? What is the motive? Why not create a frontend for every single site on the internet then?

It seems a little pointless to me.

**Comment by citizenserious** [comment]
Wikiless has been taken down from Codeberg (https://news.ycombinator.com/item?id=33101301)

**Comment by sjehuda** [comment]
> an already perfectly okay non tracking website

Says who?
How can you know?
Did you read the campaign of (defunct) Scroogle (scroogle.org) at the time when they revealed that the "already safe" website shares (no sells) private information with notorious companies?

In any case, I'll do my best to keep Wikiless featured in [my project](https://openuserjs.org/scripts/sjehuda/FREEdirector).

**Comment by f478ccf2** [comment]
And I can argue the same for my side. Wikipedia has been secretly infiltrated by the NSA and is collecting all your personal data?
Says who?
How can you know?

**Comment by sjehuda** [comment]
Notice! I'm not claiming anything.

Your argument, which I don't find appealing, shouldn't and wouldn't
bring any legitimacy not to maintain a proxy software (or any type of
software) as Wikiless.

Your argument, in some way, looks like this:

Richard: I grow my own food.
Miriam: I grow some foods and I also buy from the market.
David: Why do you even grow anything when you can buy anything from
the market? <-- BAD QUESTION

Your argument seems like the so called question of David.

Nevertheless, I'm for people to write and say whatever they want, and
even write any software they want.

Please don't be surprised to get responds that oppose your opinion,
which, as I stated is not appealing.

**Comment by f478ccf2** [comment]
I agree. I've edited my issue, to be more clear and concise about my issue with WikiLess.

**Comment by zekooooo** [comment]
One argument in favor of Wikiless is it can use the (old) desktop UI.

That one is a real pain to use on Wikipedia without registering, they never added something like old.reddit and they want you to register if you want to use it regularly.

I even prefer it over m.wikipedia on my phone when the page is long

**Comment by f478ccf2** [comment]
> Notice! I'm not claiming anything. Your argument, which I don't find appealing, shouldn't and wouldn't bring any legitimacy not to maintain a proxy software (or any type of software) as Wikiless. Your argument, in some way, looks like this: Richard: I grow my own food. Miriam: I grow some foods and I also buy from the market. David: Why do you even grow anything when you can buy anything from the market? <-- BAD QUESTION Your argument seems like the so called question of David. Nevertheless, I'm for people to write and say whatever they want, and even write any software they want. Please don't be surprised to get responds that oppose your opinion, which, as I stated is not appealing.

just realized u r a fucking jew nigga your fucking mosad has already infiltrated mass sites... fuck nig gers

**Comment by sjehuda** [comment]
Yes.

- I am a jew
- I am not a nigger.
- I am not affiliated with that organization.
- I am aware that wikipedia is a mean of propaganda and false information.
- https://www.fivefilters.org/2023/glenn-greenwald-on-wikipedia-bias/

---

Admins.

I am for (almost) all forms of expression and speech.

I see no problem with any speech of this thread.

Please. Do not censor any speech here, as censorship would harm me indirectly.
