### ISSUE TITLE
No redirect for youtube.com/c/channel_name

### ISSUE THREAD

**Issue by jorgesumle** [SimonBrazell/privacy-redirect#41]
`https://www.youtube.com/c/atareao` didn't redirect me to invidious instance. I'm using version 1.1.22 on Firefox.

**Comment by SimonBrazell** [comment]
Hi @jorgesumle please try v1.1.23, there was a bug in v1.1.22 that was caused by the whitelist changes.

**Comment by jorgesumle** [comment]
It redirects me to the trending page now: https://yewtu.be/feed/trending

**Comment by SimonBrazell** [comment]
Might be an issue with the instance you're using, I'll have to do some testing but I recall channels working in the past.

**Comment by SimonBrazell** [comment]
Just tested this on Firefox and Chrome, navigating to https://www.youtube.com/c/atareao correctly redirects to https://invidious.snopyta.org/channel/UCP8dTCaLNJFxfklb_GNqe6A, that's using https://invidious.snopyta.org as the instance of course, give that a try and let me know if that works for you.

**Comment by jorgesumle** [comment]
Yes, it works. The issue is with the instance yewtu.be
