### ISSUE TITLE
Bibliogram redirects to / and not /u/$username

### ISSUE THREAD

**Issue by acidjames** [SimonBrazell/privacy-redirect#45]
Hi folks,

first of all, thanks for this very interesting and useful extension.

I've noticed that a bibliogram page is as follows 

https://bibliogram.art/u/$username

The extension redirects to /$username so it doesn't work as expected.

Is this normal ?

Thanks,

**Comment by SimonBrazell** [comment]
Hi @acidjames thanks for letting me know, I'll look into it. Should just redirect to /u/username not sure where the $ is coming from...

**Comment by acidjames** [comment]
Don't worry @SimonBrazzel, $ is just to make sure i'm talking about a "variable". (php bad habits)

**Comment by acidjames** [comment]
I'll have to add that it works as it's supposed to for other accounts i've tried today, except : 

https://www.instagram.com/parkingdance/

which is the page for my friends band, i guess it's not intepreted as a "user" ?

I land on a bibliogram page that says "404 maybe try user @parkingdance"

**Comment by SimonBrazell** [comment]
Oh right sorry I misunderstood, so there are some usernames that aren't being redirected correctly for you then? I'll see if I can work out what is up with https://www.instagram.com/parkingdance/ are there any others? 

All user accounts should redirect to `/u/$username` but there are some exceptions that might be interfering with your friends username.

I thought I'd made a mistake in the code somewhere and accidentally put double `$` 😀

**Comment by SimonBrazell** [comment]
Found the issue, that username is getting caught by the `instagramReservedPaths` regex, I'll fix it up now and do a new build.

**Comment by SimonBrazell** [comment]
Okay should be fixed now in [v1.1.24](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.24) which I've pushed to AMO and Chrome webstore, if you are on Chrome then you'll have to wait a few days for the release (Google is super slow to review and release updates...).

Your friend's band sounds interesting, I'm bit of a fan of post punk 😀

**Comment by acidjames** [comment]
Cool ! And thanks again for your plugin, it's dope

if you want a good track to listen on tutube you can look for "parking dance - wannabe", cheers

**Comment by SimonBrazell** [comment]
> if you want a good track to listen on youtube you can look for "parking dance - wannabe"

I like it! Now I want to go see some live music... lousy lockdowns 🙁
