### ISSUE TITLE
Version number doesn't fit background

### ISSUE THREAD

**Issue by TotalCaesar659** [SimonBrazell/privacy-redirect#52]
Version number doesn't fit background in 1.1.28 (Lubuntu 20.04, Firefox 76.0).
![Screenshot from 2020-05-19 17-55-26](https://user-images.githubusercontent.com/14265316/82342683-97732180-99fa-11ea-8006-a5ebb43e0a41.png)

**Comment by SimonBrazell** [comment]
Had some problems with this on my machine also, should be an easy fix... 🙂

**Comment by SimonBrazell** [comment]
This should be fixed in v1.1.29 but let me know if it isn't, couldn't reproduce on my machine.

**Comment by TotalCaesar659** [comment]
Thank you vary much! It works alright now.
![1](https://user-images.githubusercontent.com/14265316/82398519-b3f37600-9a5b-11ea-9e1e-09f1f1227695.png)

**Comment by SimonBrazell** [comment]
No worries thanks for the PR and all your help!
