### ISSUE TITLE
Always allow fullscreen for embeds

### ISSUE THREAD

**Issue by B0pol** [SimonBrazell/privacy-redirect#53]
Hi, YouTube embeds by default block fullscreen. But you 
modify that by adding `allowfullscreen` attribute in iframe tag.

It's annoying not to be able to watch in fullscreen just because the website decided or because they didn't know about `allowfullscreen` attribute. Let me decide what I want.

**Comment by SimonBrazell** [comment]
Hi @B0pol are you asking if we can add an attribute to the iframe within the site? I'm not sure that's possible with the currently level of permissions the extension has unfortunately.

**Comment by SimonBrazell** [comment]
The only way I can think of for editing site content with the current permissions would be to load a content script on the page, but extensions have to declare which sites they want to do this on ahead of time in the manifest and given embedded videos can be on any site, I'd have to target every site with the script, which isn't ideal...

**Comment by B0pol** [comment]
> Hi @B0pol are you asking if we can add an attribute to the iframe within the site? I'm not sure that's possible with the current level of permissions the extension has unfortunately.

That was my initial idea, yes.
Indeed I agree with you, it's a rare situation, not everyone is facing this case, therefore it's better not to increase permissions or workaround with a script on every websites.

I'll just right click, copy URL, and edit the url from `https://<invidious_instance>/latest_version?id=<video_id>&itag=<itag>` to `https://<invidious_instance>/watch?v=<video_id>` until my request https://github.com/omarroth/invidious/issues/1188 will be granted.

**Comment by SimonBrazell** [comment]
Yeah bit of a pain, I could add the content script and have it look specifically for youtube iframes but I'm sure there would be unintended side-effects of doing that on every page or something else I haven't considered.

**Comment by SimonBrazell** [comment]
Perhaps this is a feature I could add to the extension though, a 'right-click' context menu for embedded videos that has an option to open it in Invidious in a new tab or something like that?
