### ISSUE TITLE
Embedded Google Maps do not display

### ISSUE THREAD

**Issue by jones137** [SimonBrazell/privacy-redirect#54]
Example 1: https://www.walmart.com/store/finder
Example 2: https://www.alsen.pl/sklepy

The area where map should be shown is empty. Once I disable OSM redirection and reload, it displays correctly. Redirection of Google Maps URLs works fine though.

**Comment by SimonBrazell** [comment]
Hi @jones137 thanks for letting my know, I'll look into both these cases. The maps redirects likely still need a bit of work, particularly embedded maps, I remember at the time it was added myself and one of the contributors had trouble finding some examples of embedded maps to test on.

**Comment by SimonBrazell** [comment]
Okay I've had a closer look at this now and unfortunately it's not something I can fix. These sites use the Google Maps JS API to build the map so there is nothing to redirect except the call to `maps.googleapis.com/maps/api/js` to load the javascript API files, which is what the extension is currently redirecting (mistakenly) to OSM, and breaking the page.

There is no compatible OSM replacement for the Google Maps JS API (that I know of) that we could use here so the only thing to do is stop redirecting the `maps.googleapis.com/maps/api/js` calls so at least the regular Google map loads correctly.
