### ISSUE TITLE
Within the start of a new Firefox session, redirects are unreliable

### ISSUE THREAD

**Issue by jones137** [SimonBrazell/privacy-redirect#55]
Related issue on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1630024
Related issue for a similar "Redirector" addon: https://github.com/einaregilsson/Redirector/issues/195

This addon suffers from it too. If you open a new Firefox session and then quickly type youtube.com, it will sometimes load normal YouTube instead of redirecting. It's not easy to 100% reproduce though, it's kind of a lottery.

**Comment by SimonBrazell** [comment]
Hmm yeah, looks like a limitation of Firefox, which I can't really do anything about, thanks for bringing it to my attention though! 🙂

**Comment by grahamperrin** [comment]
Try Mozilla bugs [1378459 - (webextensions-startup) [meta] Allow some addon functionality to load prior to any content loading](https://bugzilla.mozilla.org/show_bug.cgi?id=1378459), [1630024 - When first staring firefox addons don't start fast enough. Temp-container doesn't open the tab in a container, Redirector doesn't redirect](https://bugzilla.mozilla.org/show_bug.cgi?id=1630024) and so on.
