### ISSUE TITLE
On a fresh session, Invidious parameters are not in effect when going to it directly

### ISSUE THREAD

**Issue by jones137** [SimonBrazell/privacy-redirect#56]
If you go directly to an invidious video URL on a new session, like https://invidio.us/watch?v=LWJPn-xMu0s , it will load it without proxy or dark mode even if you have it enabled. Once you navigate to another subpage they enable themselves, but it's still a bit dangerous (call to Google).

**Comment by SimonBrazell** [comment]
This should only happen on the first load of invidious, all subsequent should persist your settings, is that what you're seeing?

The plugin creates a cookie for Invidious that persists your settings (e.g. dark mode, etc.) but this doesn't happen unless you've navigated to the site, as the cookie code is loaded as a content script on the Invidious instance you've chosen. Which I know is a bit of a gap but I figured the normal use case for this extension is to redirect YouTube to Invidious, in doing so it would include your settings as a query string in the URL (e.g. `?local=true&dark_mode=true`), and when this page loads it will also set the cookie as mentioned above, so all subsequent loads should persist your settings, does that make sense? That is unless it isn't behaving that way for you... 🙂

**Comment by SimonBrazell** [comment]
Correction, I just checked the code, the cookie code is loaded on the following pages regardless of whether they are your selected instance or not:

```
        "*://invidio.us/*",
        "*://invidio.us/*",
        "*://invidious.snopyta.org/*",
        "*://invidiou.sh/*",
        "*://yewtu.be/*",
        "*://yt.maisputain.ovh/*",
        "*://invidious.toot.koeln/*",
        "*://invidious.ggc-project.de/*",
        "*://invidious.toot.koeln/*",
        "*://kgg2m7yk5aybusll.onion/*",
        "*://axqzx4s6s54s32yentfqojs3x5i7faxza6xo3ehd4bzzsg2ii4fv2iid.onion/*",
        "*://fz253lmuao3strwbfbmx46yu7acac2jz27iwtorgmbqlkurlclmancad.onion/*",
        "*://qklhadlycap4cnod.onion/*",
        "*://c7hqkpkpemu6e7emz5b4vyz7idjgdvgaaa3dyimmeojqbgpea3xqjoid.onion/*",
        "*://mfqczy4mysscub2s.onio/*n"
```

**Comment by SimonBrazell** [comment]
Just thought of something, this issue will occur again in subsequent browsing sessions if you delete cookies between sessions... is that what you are experiencing? If so perhaps you can make an exception for Invidious so the `PREFS` cookie remains across sessions.

**Comment by jones137** [comment]
Yes, I clear cookies and all site data on quitting the browser. Isn't there a way to create a cookie before loading the page for the first time?

**Comment by SimonBrazell** [comment]
No unfortunately the cookie needs to be set on the page it's used, and the content script is already being run as early as it can be (`document_start `). Can you add an exception and persist cookies for Invidious?

**Comment by jones137** [comment]
I guess I can, but maybe the first time I load the instance, there could be parameters in the URL automatically added? For example currently if I enter youtube.com, I get redirected to https://invidious.snopyta.org/?local=true&quality=hd720&dark_mode=true and once I navigate to another subpage the cookie takes the parameters' job.

**Comment by SimonBrazell** [comment]
If the extension does the redirect then the parameters will be present, when you navigate to Invidious outside of the extension then they won't be present, to do this I'd have to redirect Invidious requests to invidious which could potentially result in an endless loop (not tested this) and otherwise not be ideal anyway. 

I think the cookie solution is a good one for the context of this extension, as long as you are willing to allow cookies and persist them outside of a single browsing session.

**Comment by SimonBrazell** [comment]
Closing for now, let me know if you still have problems with the cookie solution.
