### ISSUE TITLE
Privacy Redirect removed from AMO

### ISSUE THREAD

**Issue by atomGit** [SimonBrazell/privacy-redirect#58]
just curious as to why it was removed

**Comment by SimonBrazell** [comment]
Hi @atomGit here's the response I got from Mozilla:

> Hello,
> 
> 
> Due to issues discovered during the review process, your add-on Privacy Redirect has been disabled on addons.mozilla.org and no longer appears in the gallery. Users who have previously installed your add-on will be able to continue using it.
> 
> Please see the reviewer's comments below for more information.
> 
> ********
> Details:
> This add-on didn&#39;t pass review because of the following problems:
> 
> 1) We don&#39;t allow add-ons to use remote scripts because they can create serious security vulnerabilities. We also need to review all add-on code, and this makes it much more difficult. Please insert those scripts locally from your add-on code.
> eg:
> assets/iframe_api.js
> 
> Reviewer:
> Crypto
> 
> ********

The script in question is [here](https://github.com/SimonBrazell/privacy-redirect/blob/master/assets/iframe_api.js), it is a YouTube script that loads embedded video iframes in sites, I host it within the app to prevent a further call to YT servers to retrieve it when you visit a site that uses it. I need to work on a workaround so I can publish the extension again on AMO, either removing the script or further inspecting it to determine what calls are made and seeing if I can host the scripts they load also.

**Comment by SimonBrazell** [comment]
Upon reading it again though they may be saying something else, perhaps I need to ask them for clarification?

**Comment by SimonBrazell** [comment]
It says 

> Please insert those scripts locally from your add-on code
> eg:
> assets/iframe_api.js

but that's what I've done with `iframe_api.js`, I thought the problem was that script was loading other remote scripts, need to look into it further, haven't had time since it was taken down yesterday morning.

**Comment by SimonBrazell** [comment]
Just responded to the reviewer with the following:

> Thanks for the response, I wasn't aware of this problem, the `assets/iframe_api.js` and `assests/www-widgetapi.js` are YouTube assets that I host locally within the extension to prevent sites that use them from contacting YouTube's servers to retrieve them. I'm just after a bit of clarification around the issue, is the problem that I am hosting these scripts locally and they are difficult to inspect and review, or is it because one or both of these scripts are loading some remote code in their execution?

**Comment by SimonBrazell** [comment]
Mozilla's response:

Crypto wrote:

> Hello
> 
> >  I'm just after a bit of clarification around the issue, is the problem that I am hosting
> these scripts locally and they are difficult to inspect and review, or
> is it because one or both of these scripts are loading some remote code
> in their execution?
> 
> Your 'locally hosting' is remote to the add-on and the add-on users so both above mentioned scenarios are actually the same AFA addon code is concerned.
> All executable code must be packed within the extension.

To which I replied:

> So having JS assets declared in the extension's `manfest.json` file as `web_accessible_resources` and bundled with the extension still counts as remote?
> 
> Line 76-79 of the extension's `manifest.json` file:
> 
> "web_accessible_resources": [
>     "assets/iframe_api.js",
>     "assets/www-widgetapi.js"
>   ],
> 
> And line 203-209 of the extension's `background.js` file where these local files are used:
> 
> if (url.pathname.match(/iframe_api/)) {
>     // Redirect requests for YouTube Player API to local files instead
>     return browser.runtime.getURL('assets/iframe_api.js');
>   } else if (url.pathname.match(/www-widgetapi/)) {
>     // Redirect requests for YouTube Player API to local files instead
>     return browser.runtime.getURL('assets/www-widgetapi.js');
>   }
> 
> This code is only executed if the domain of the request caught in the `browser.webRequest.onBeforeRequest` listener matches one of the domain's this extension targets for YoutTube redirects.
> 
> I don't see how this counts as external to the extension? How else should I achieve this using the browser extension API?

**Comment by SimonBrazell** [comment]
Bit confusing... see what they say in response, if they won't allow it then I'll just remove this feature I gues. 

Bit of a let down as it means pages with embedded YT videos using this service will have to send a request to YT to load these assets before the extension can do it's thing, which is a bit step back if you're trying to avoid sending any requests to Google's servers.

**Comment by atomGit** [comment]
from assets/iframe_api.js
is this the script they're referring to? :

`https://s.ytimg.com/yts/jsbin/www-widgetapi-vflYl14TA/www-widgetapi.js`

i'm not a coder, but it looks like this script is being pulled from s.ytimg.com - maybe that's why they're complaining?

**Comment by SimonBrazell** [comment]
Got this response:

> Please note the referenced file in the review:
> assets/iframe_api.js
> 
> var a = document.createElement('script');
> a.src = 'https://s.ytimg.com/yts/jsbin/www-widgetapi-vflYl14TA/www-widgetapi.js';
> var b = document.getElementsByTagName('script')[0]; 
> b.parentNode.insertBefore(a, b);
> 
> Above is remote script injection.
> 
> Please also note that adding random spaces does not change the fact that the code is minified and sources would be required for all minified code e.g.:
> assets/iframe_api.js
> assets/www-widgetapi.js

So it's clear now, looks like I'm going to have to remove these files, and allow a request that goes out to Google servers to fetch these now instead. I'll fix this up shortly and resubmit to AMO.

**Comment by SimonBrazell** [comment]
Okay new version pushed to the store that no longer includes local versions of these assets, and now does not redirect requests made for them anymore 🙁
