### ISSUE TITLE
Embedded videos don't work

### ISSUE THREAD

**Issue by funnyflowerpot** [SimonBrazell/privacy-redirect#6]
Hello!

First, thank you for this handy add-on! Combining redirects to those sites into one add-on is really awesome. Please keep up the good work!

For a while now I have problems with embedded videos. They are not shown, I only get a black rectangle. Please find example output from the Firefox developer console below. I get such and similar output from different pages, varying in the number of repetitions of the same message. The last part on each line is the (temporary) file name, line and column number. (Sorry for the bad format.) Amid that jungle, two URLs shine out:

* https://invidio.us/yts/jsbin/www-embed-player-vfl19rSh2/www-embed-player.js
* https://www.youtube.com/yts/jsbin/player_ias-vfl22ubNH/en_US/base.js

Interestingly, only one URL is redirected to Invidious in the example output (a different problem?). On some pages I get errors with the both URLs, but with the first URL already rewritten to Invidious. When I try to access those URLs, I get redirected to the homepage of Invidious, which fits the error messages about content of unexpected MIME type, as far as I can see. However, fetching those files with `invidio.us` as domain also leads to the homepage in Ungoogled Chromium.

I think this is a problem of this add-on, because I tested with [another add-on](https://addons.mozilla.org/en-US/firefox/addon/invidious-redirect/) that redirects to Invidious and with that I don't get this error and the videos play. However, I still get communication with YouTube and repeated output of an error message, so this specific (unmaintained) add-on is not the best [code example](https://github.com/doronbehar/invidious-redirect/blob/768a0ac36fb1b6832705848a54a16aae9aa0d95a/background.js).

Happy to help testing. Please let me know, if I can provide more information. Thanks!

```
The resource from “https://invidio.us/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). 9B9SId9_lpQ
The script from “https://invidio.us/” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. 2 uMG8BMrOO00
The script from “https://invidio.us/” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. _w0oBujJ9P4
The resource from “https://invidio.us/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). 9B9SId9_lpQ
The script from “https://invidio.us/” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. 2 DbKzNqEIDdY
The script from “https://invidio.us/yts/jsbin/www-embed-player-vfl19rSh2/www-embed-player.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. DbKzNqEIDdY
Loading failed for the <script> with source “https://www.youtube.com/yts/jsbin/www-embed-player-vfl19rSh2/www-embed-player.js”. DbKzNqEIDdY:3:1
The resource from “https://invidio.us/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). 9B9SId9_lpQ
The script from “https://invidio.us/” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. DbKzNqEIDdY
Loading failed for the <script> with source “https://www.youtube.com/yts/jsbin/player_ias-vfl22ubNH/en_US/base.js”. DbKzNqEIDdY:4:1
ReferenceError: yt is not defined DbKzNqEIDdY:12:1
The resource from “https://invidio.us/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). _w0oBujJ9P4
The resource from “https://invidio.us/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). uMG8BMrOO00
Loading failed for the <script> with source “https://www.youtube.com/yts/jsbin/www-embed-player-vfl19rSh2/www-embed-player.js”. uMG8BMrOO00:3:1
The script from “https://invidio.us/” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. uMG8BMrOO00
Loading failed for the <script> with source “https://www.youtube.com/yts/jsbin/player_ias-vfl22ubNH/en_US/base.js”. uMG8BMrOO00:4:1
ReferenceError: yt is not defined uMG8BMrOO00:12:1
The resource from “https://invidio.us/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). _w0oBujJ9P4
Loading failed for the <script> with source “https://www.youtube.com/yts/jsbin/www-embed-player-vfl19rSh2/www-embed-player.js”. _w0oBujJ9P4:3:1
The resource from “https://invidio.us/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). 9B9SId9_lpQ
Loading failed for the <script> with source “https://www.youtube.com/yts/jsbin/www-embed-player-vfl19rSh2/www-embed-player.js”. 9B9SId9_lpQ:3:1
The resource from “https://invidio.us/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). _w0oBujJ9P4
Loading failed for the <script> with source “https://www.youtube.com/yts/jsbin/player_ias-vfl22ubNH/en_US/base.js”. _w0oBujJ9P4:4:1
ReferenceError: yt is not defined _w0oBujJ9P4:12:1
The resource from “https://invidio.us/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). 9B9SId9_lpQ
Loading failed for the <script> with source “https://www.youtube.com/yts/jsbin/player_ias-vfl22ubNH/en_US/base.js”. 9B9SId9_lpQ:4:1
ReferenceError: yt is not defined 9B9SId9_lpQ:12:1
```

**Comment by SimonBrazell** [comment]
Hello @funnyflowerpot!

Thanks for the feedback and code examples, I'll see what I can put together, this plugin is still pretty basic, I'll put some more time into working out this issue.

Do you happen to have the URL of the original page that includes the broken embedded videos that I can use for troubleshooting and testing the fix? I'm sure I can find one myself but I want to make sure I'm addressing the specific issue you are experiencing.

**Comment by ToughGuyKunio** [comment]
I have the same issue, example on: https://www.reddit.com/r/videos/

**Comment by funnyflowerpot** [comment]
Hey @SimonBrazell, thanks for the response.

I rechecked and I believe this applies to any embedded video. I confirm the example by @ToughGuyKunio. You can seem to pick any video, like [this](https://pages.github.com/) or [this (click on "Get started")](https://joinmastodon.org/) for example.

**Comment by SimonBrazell** [comment]
@funnyflowerpot looks to be specific to Firefox, I just visited the [link](https://www.reddit.com/r/videos/) supplied by @ToughGuyKunio above using Ungoogled Chromium and the embedded videos load, although not all, some display this message - `The media could not be loaded, either because the server or network failed or because the format is not supported.`

I'm still not sure what the root cause of this issue is yet, I tried using the code in the repo you supplied but the issue was still present on Firefox.

**Comment by ToughGuyKunio** [comment]
I just confirmed that embedded videos works (on Firefox) with this extension: https://github.com/hutattedonmyarm/invidious-redirect if that helps

**Comment by ToughGuyKunio** [comment]
I tried this [Invidious Redirect extension fork](https://addons.mozilla.org/en-US/firefox/addon/invidious-redirect-2/) ([code](https://github.com/hutattedonmyarm/invidious-redirect)). I use Firefox 72 on Manjaro Linux. All embedded videos works (except those that don't work on main invidio.us site). If it helps.

**Comment by SimonBrazell** [comment]
Thanks @ToughGuyKunio, I tried a few variations on that code you posted just now to no avail, might need to spend some more time on this to figure it out. One difference I can see is that the background script on the other repo listens for requests from `all urls` and only for `main_frame` and `sub_frame` types while this extension listens for only targeted domains and more types so perhaps there is something in that...

**Comment by SimonBrazell** [comment]
Okay so it seems I can fix this by listening for `"<all_urls>"` instead of the current targeted list:

 `"*://twitter.com/*", "*://www.twitter.com/*", "*://mobile.twitter.com/*", "*://youtube.com/*", "*://www.youtube.com/*", "*://youtube-nocookie.com/*", "*://www.youtube-nocookie.com/*", "*://m.youtube.com/"`

And limiting the request types to `"main_frame", "sub_frame"` instead of: 

`"main_frame", "sub_frame", "stylesheet", "script", "image", "object", "xmlhttprequest", "other"`. 

But one of the aims I had with this extension was to do it with minimal permissions, giving the extension access to all URLs seems like overkill, maybe I should keep looking...

**Comment by SimonBrazell** [comment]
Found the problem, I misinterpreted the way that the `browser.webRequest.onBeforeRequest.addListener()` filters worked. 

Because I am only listening for requests from specific domains (`twitter.com`, `youtube.com`, etc.) I am missing any requests from iframes that are embedded within another site as they originate from whichever site they are embedded in and so aren't matched by my filters. Even though the request is for a domain in my filters list it's `originUrl` is something else and it is this field that the filters are matched on (well either `originUrl` or `documentUrl`).

So it appears in order to resolve this issue I do indeed have to listen for `<all_urls>`, bit of a bummer, doesn't seem to be any way around it.

**Comment by SimonBrazell** [comment]
New version (v1.1.3) that includes that change is pending review on the stores. Please let me know if you encounter any issues with it.

**Comment by ToughGuyKunio** [comment]
It works for me now, thanks a lot!

**Comment by SimonBrazell** [comment]
Glad to hear, lets hope that it gets approved on the Chrome store now, changing the permissions means it has to go through the review process... still waiting for it to be reviewed.

**Comment by funnyflowerpot** [comment]
Thanks a lot @SimonBrazell for the quick responses! Works for me, too!

**Comment by SimonBrazell** [comment]
No worries, just noticed the update went live on the Chrome store today also.
