### ISSUE TITLE
YouTube Studio

### ISSUE THREAD

**Issue by matteqa** [SimonBrazell/privacy-redirect#60]
Attempts to access studio.youtube.com (for video uploads and analytics) should not be redirected as they are not handled by Invidious.

**Comment by SimonBrazell** [comment]
No problem, this must be a regression in one of the recent builds as I did have an exception in place for these routes already, should be a quick fix.

**Comment by SimonBrazell** [comment]
Should be fixed in v1.1.32 due to go live on AMO shortly.
