### ISSUE TITLE
After update to 1.1.32 Nitter redirect on Chrome only works after force refresh

### ISSUE THREAD

**Issue by tux93** [SimonBrazell/privacy-redirect#61]
Since 1.1.32 was rolled out on Chrome / Chromium the Nitter redirect no longer works.

Clicking a Twitter link opens Twitter, the redirect only happens if I force refresh the page with CTRL+R or SHIFT+F5, I'm not sure whether this is a caching problem on my end or a general issue.

On Firefox Twitter links are correctly redirected when opening the page the first time.

**Comment by SimonBrazell** [comment]
Hmm okay I'll look into it, I did test last night on both Chromium and Firefox but perhaps I missed something.

**Comment by SimonBrazell** [comment]
This isn't my experience, can you make sure you have the advanced option `Proactively remove Twitter service worker` enabled, Twitter loads a service worker that interrupts with redirects.

**Comment by SimonBrazell** [comment]
There does seem to be something up though, I just disabled that option and then was stuck with Twitter, with redirects failing, can you confirm you didn't have that option enabled before?

**Comment by tux93** [comment]
The option is enabled currently, I'm not sure if it was disabled at some point

I just tried removing the extension and installing again but the behaviour didn't change

**Comment by tux93** [comment]
What does work for me is enabling the extension in incognito mode and opening the link in a private tab, that will redirect to Nitter immediately

**Comment by SimonBrazell** [comment]
Yeah okay there is definitely a problem, it seems to be related to the Twitter service worker, and the script I've put in to remove it as previously it was hijacking the extension redirects. It was that script that made it difficult to get the 'view on Twitter' links working.

**Comment by SimonBrazell** [comment]
Having some difficulty with this, not sure why the behaviour is different on Chrome vs Firefox, I'm going to disable the Nitter - 'View on Twitter' feature on Chrome and leave it as is for Firefox for now, that way Twitter redirects should work as they did before.
