### ISSUE TITLE
Redirect nitter same as invidious

### ISSUE THREAD

**Issue by 2oq2o5** [SimonBrazell/privacy-redirect#62]
Greetings! When you click on the redirection in invidious to visualize the content in youtube, it sends you there correctly and you can even continue browsing youtube without being redirected to invidious again.
It's not the same with nitter, you can't even see a single tweet and it immediately returns to nitter.

I'm very interested in accessing twitter occasionally so I can save bookmarks and pages or use certain addons, but it's tedious having to disable and re-enable privacy-redirect every time. Is there any way for them to have the same behavior?

Thank you very much for this great extension!

**Comment by SimonBrazell** [comment]
Hi @2oq2o5 I'm going to look at the Nitter / Twitter stuff again this evening, seems I might have messed up the implementation of the 'view on Twitter' links. Problem is they are made much more complex than the same Invidious feature because of the Twitter service worker removal script I've put in place...

**Comment by 2oq2o5** [comment]
The redirect works well, now. When I read about "service worker" I remembered that I have an addon to block them and I thought that it could generate some conflict, but no. It simply all works fine, I've been appreciating the problem for a few weeks but it seems that it was fixed just in the last commit, I probably should have looked first. I'm so sorry... I'll buy you a coffee!

**Comment by SimonBrazell** [comment]
No don't be sorry, I have had another user mention problems with the latest build and Nitter redirects so it definitely needs looking at, I sometimes code late at night, which results in mistakes like this happening, probably should stop doing that 🙂
