### ISSUE TITLE
redirect youtube music

### ISSUE THREAD

**Issue by B0pol** [SimonBrazell/privacy-redirect#63]
https://music.youtube.com/playlist?list=OLAK5uy_l2a-m-HR606XITpP6VAQUa3Q8Utq7B00o can be redirected to https://invidio.us/playlist?list=OLAK5uy_l2a-m-HR606XITpP6VAQUa3Q8Utq7B00o for example

**Comment by SimonBrazell** [comment]
Oh cool, didn't know about this, will do!

**Comment by SimonBrazell** [comment]
This should be implemented in v1.1.33.
