### ISSUE TITLE
Whitelisted URLs are still redirected

### ISSUE THREAD

**Issue by tux93** [SimonBrazell/privacy-redirect#64]
For example adding whitelist entries for Youtube Watch Later (https://www.youtube.com/playlist?list=WL) or Twitter Notifications (https://twitter.com/notifications) those are still redirected to Invidious / Nitter

This happens on both Firefox and Chromium, I suspect this is related to #38 also not working

**Comment by SimonBrazell** [comment]
I think I missed something with the Twitter whitelist so I'm not surprised that doesn't work, but the YT whitelist should work, I'll see if I can work out the issue.

**Comment by SimonBrazell** [comment]
Okay so I can confirm the whitelist needs more work, it was only built with a pretty narrow focus in mind, to avoid embedded redirects on `https://cytu.be/` which it does, but it doesn't apply to normal redirects atm.

**Comment by SimonBrazell** [comment]
It was only checking to see it the `initiator` matched an entry on the whitelist, not the requested `url`, see if I can add this feature now.

**Comment by SimonBrazell** [comment]
Should be fixed now in v1.1.34 but let me know if there are still problems.

Thanks for letting my know about these issue btw, it's much appreciated.
