### ISSUE TITLE
Suggestion: OpenStreetMap Redirects for embedded maps only.

### ISSUE THREAD

**Issue by Cade66** [SimonBrazell/privacy-redirect#65]
Hi,

I'm running flawlessly _Privacy Redirect_ 1.1.34 / Firefox 77.0.1 (x64).
I appreciate and use the _Only redirect embedded video to Invidious_ option.
Maybe would it be pertinent to have a similar option for the _OpenStreetMap_ Redirects, something such as _Only redirect embedded maps to OpenStreetMap_

Just a suggestion!

**Comment by SimonBrazell** [comment]
Hi @Cade66 glad to hear it's running well for you. 🙂

This is a good idea however the OSM support for embedded maps is not complete, it only works currently if the Google map is embedded as an iframe, not if the site has made use of the Google Maps JS API. I don't encounter many embedded maps while browsing so I'm not sure how widespread the use of the API is but if majority of sites use that method instead then I think you will be disappointed with the results.

Do you encounter many embedded maps in your travels and if so do they redirect to OSM nicely for you?

**Comment by Cade66** [comment]
Hi @SimonBrazell , I get the idea, thanks. To answer your question, truth is I don't encounter many embedded maps but that when I do I appreciate having them handled by Privacy Redirect, which has done the work flawlessly up to now. On another hand Google Maps offers more than plain maps which is why I hesitate to activate the OpenStreetMap Redirects. Of course it's always possible to quickly toggle from the toolbar button. Given what you indicate I'd consider my suggestion as obsolete. Thanks!

**Comment by SimonBrazell** [comment]
Hi @Cade66 this is now possible by creating the following exception in the options menu:

`https?:\/\/www\.google\.com\/maps(?!\/embed).*` as a `RegExp`

Let me know if this doesn't work for you and I'll reopen.

**Comment by Cade66** [comment]
@SimonBrazell thanks for following up this post of mine and proposing a workaround via this RegExp set as an exception.
I'm answering because having experienced Google Maps and embedded Google Maps leads to a "it works, yes and no"

It works, yes : basically non-embedded Google Maps appear **in** Google Maps and embedded Google Maps **with** OpenStreetMap : great.
It works, no : sites which call Google Maps for more than maps won't run correctly, not many but at least this one: [InstantStreetView](https://www.instantstreetview.com/
), but this could be resolved only with a whitelist feature, far beyond the scope of Privacy Redirect.

It's good to know that Privacy Redirect has the possibility of using a RegExp exception to fulfill my request, "_OpenStreetMap Redirects for embedded maps only_", and it works.
In my concern though redirecting Google Maps, embedded or not, is not a feature I'll use, simply because I seldom encounter embedded Google Maps, when I do I bypass them (uBlock Origin + CSS) when not strictly required such as in [GeoTool](https://iplookup.flagfox.net/). But of course the Maps Redirect option is and remains most valuable for many users. Thanks again for your work, the extension is a daily privacy companion, most appreciated especially with Invidious instances which are, by the way, getting better and better.
