### ISSUE TITLE
Add peertubeify

### ISSUE THREAD

**Issue by stemy2** [SimonBrazell/privacy-redirect#67]
Hello,

I'd like to be redirected to the peertube instance if existing or to the invidious instance if not. Is it possible to add a such parameter into your extension ?

**Comment by SimonBrazell** [comment]
I can look into it. Sorry I'm not really familiar with the ins and outs of PeerTube, can you give some examples of how this would work?

**Comment by stemy2** [comment]
There is already a Peertubeify extension, maybe it could inspire you.

https://gitlab.com/Cha_deL/peertubeify

**Comment by narFnarF** [comment]
Since Peertubeify already exists and works well, a user just have to install both. No need to add every feature in this extension. (but that's just my opinion)

**Comment by theotheroracle** [comment]
it seems like the extensions wouldn't be especially compatible ?

**Comment by theotheroracle** [comment]
if this extension at least detected the peertubify extension somehow and made allowances for it maybe but that sounds quite difficult

**Comment by stemy2** [comment]
Actually, there's no need to integrate peertubeify into the add-on. If you install the add-ons separately, it try to redirect to peertube, and if it fails, redirects to invidious.
