### ISSUE TITLE
YouTube: links to channels without /channel/ doesn't works

### ISSUE THREAD

**Issue by ToughGuyKunio** [SimonBrazell/privacy-redirect#7]
Links to channel pages like `https://www.youtube.com/pewdiepie` doesn't work, only links with _/channel/_ or _/user/_, like `https://www.youtube.com/channel/pewdiepie` works.

**Comment by SimonBrazell** [comment]
Thanks @ToughGuyKunio I'll look into this.

**Comment by SimonBrazell** [comment]
This seems to be an issue with Invidious as I can see the plugin is redirecting `https://www.youtube.com/pewdiepie` => `https://invidio.us/pewdiepie` as it should but then invidio.us isn't handling it properly and just defaulting to the homepage instead.

**Comment by SimonBrazell** [comment]
You can confirm this by just navigating to [https://invidio.us/pewdiepie](https://invidio.us/pewdiepie), bypassing the extension, still exhibits the undesired behaviour.

**Comment by ToughGuyKunio** [comment]
Seems omarroth fixed this, works for me now.

**Comment by SimonBrazell** [comment]
Good stuff! Thanks for following this up with them.
