### ISSUE TITLE
Options instance input fields do not display `datalist` pre-defined options

### ISSUE THREAD

**Issue by Ha1zGw** [SimonBrazell/privacy-redirect#71]
In the about:addons menu, double-clicking on the text field to change the server does not open any dialog to choose a server.

Additionally I would like to suggest a button next to the text field that removes its content, to speed up the change of the server.

Thanks for reading.

**Comment by SimonBrazell** [comment]
Hi @Ha1zGw, thanks for the issue, I've noticed this too, the datalist elements don't seem to work in the options menu  and it was actually reported to Mozilla on my behalf by one of the maintainers who submitted a [pull request](https://github.com/SimonBrazell/privacy-redirect/pull/29#issuecomment-605882258) to this project - [https://bugzilla.mozilla.org/show_bug.cgi?id=1625867](https://bugzilla.mozilla.org/show_bug.cgi?id=1625867), there was no progress for some time but I noticed just now that there are a few comments, still no resolution though, so I'll have to come up with another solution...

**Comment by SimonBrazell** [comment]
Could perhaps do something like [this](https://www.w3schools.com/howto/howto_js_autocomplete.asp) instead, shame the native HTML element made for this use case doesn't work though 🙁
