### ISSUE TITLE
Add Option to manually override light / dark mode.

### ISSUE THREAD

**Issue by smaragdus** [SimonBrazell/privacy-redirect#74]
I installed [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect) on a Chromium fork and the pop-up I get is white, screen:

![Privacy Redirect 1 1 35 - 2020-07-12 - 002](https://user-images.githubusercontent.com/9025757/87251353-c0041e80-c473-11ea-87dc-ba56d9aaa75d.png)

while in the screen-shots at [Chrome Web Store](https://chrome.google.com/webstore/detail/privacy-redirect/pmcmeagblkinmogikoikkdjiligflglb) and [Firefox AMO](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/) the pop-up is black. I sought through options but I could not find an option related to GUI/colour/theme. Is the extension theme-aware? Am I missing something? I am using [Oceanic](https://chrome.google.com/webstore/detail/oceanic/gbbacdmgjdfajabgglpjifcedoajdimg) theme.

**Comment by SimonBrazell** [comment]
Hi @smaragdus the pop-up and the rest of the add-on UI theme is determined by the system / OS light or dark colour theme. So you will need to set your OS theme to be dark in order to get the extension looking like it does in the store. Failing that it appears that you can also set `#enable-force-dark` in `chrome://flags` to ignore the OS theme and force dark mode in just the browser. Does that help?

**Comment by SimonBrazell** [comment]
I'll see if I can add an option to manually override the extension theme rather than rely on the OS theme only.

**Comment by smaragdus** [comment]
@SimonBrazell 

Thank you for the quick response. My OS is Windows 8 and as far as I know it does not support dark/light mode. I am using [Redshift Tray](https://github.com/ltGuillaume/Redshift-Tray) to automatically adjust colour temperature.

> I'll see if I can add an option to manually override the extension theme rather than rely on the OS theme only.

If it does not require too much of work this would be excellent. Thanks for this excellent extension!

Regards

**Comment by SimonBrazell** [comment]
Oh right, yes I imagine Windows 8 wouldn't have any support for this at the OS level, also discovered [an issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1644261) with Firefox that relates to this on macOS, plus anyone using Tor probably doesn't have dark mode support either, so there is a pretty good case for this feature I think.

**Comment by smaragdus** [comment]
@SimonBrazell 

Version [1.1.37](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.37) allows me to switch to dark theme manually without OS theme dependency:

**pop-up**

![Privacy Redirect 1 1 37 - 2020-07-16 - 003](https://user-images.githubusercontent.com/9025757/87694674-21d7c780-c797-11ea-8e7b-b5b392790da1.png)

**options**

![Privacy Redirect 1 1 37 - 2020-07-16 - 004](https://user-images.githubusercontent.com/9025757/87694715-30be7a00-c797-11ea-8f6d-a5df96671662.png)

Excellent work, Simon! Many thanks! This was a cosmetic issue but I really prefer the dark theme.

Off-topic- I came upon an Android app- **UntrackMe** ([Website](https://fedilab.app/wiki/untrackme/), [Source](https://framagit.org/tom79/nitterizeme), [F-Droid](https://f-droid.org/en/packages/app.fedilab.nitterizeme/)) which has 3 features:

- **Redirect**
- **Unshorten**
- **Cleanup**

Its **Redirect** feature does the same [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect) does. I suppose that you might find it useful.

Best regards
