### ISSUE TITLE
Add support to bibliogram

### ISSUE THREAD

**Issue by erotavlas-turbo** [SimonBrazell/privacy-redirect#8]
Hi,
your extension is very useful. Please add support to [bibliogram](https://bibliogram.art) (instagram alternative front-end).

**Comment by SimonBrazell** [comment]
Didn't know about bibliogram, I'll definitely add support for it!

**Comment by SimonBrazell** [comment]
Created a new release (v1.1.4) that includes support for Bibliogram redirects, currently pending review and release on the stores. 

Let me know what you think.

**Comment by SimonBrazell** [comment]
Google knocked back the submission on the Chrome Webstore for some trivial reasons, so if you are waiting on the Chromium release it might be a while longer, see how I go with the resubmission...
