### ISSUE TITLE
Make "Version" string translatable

### ISSUE THREAD

**Issue by TotalCaesar659** [SimonBrazell/privacy-redirect#82]
Please make "Version" string translatable, it looks allogenic with other languages.
![1](https://user-images.githubusercontent.com/14265316/88129484-ded78300-cbe0-11ea-81f9-1be72ecfe0e3.png)

**Comment by SimonBrazell** [comment]
Hi @TotalCaesar659 will do!

**Comment by SimonBrazell** [comment]
Implemented this in v1.1.38, might need you to add the translation though 🙂 (that's a smiley just in case you have emojis filter haha...)

**Comment by TotalCaesar659** [comment]
Thank you very much :-) [Updated](https://github.com/SimonBrazell/privacy-redirect/pull/86) Russian translation.
