### ISSUE TITLE
Unsafe innerHTML in i18n function – better approach

### ISSUE THREAD

**Issue by realpixelcode** [SimonBrazell/privacy-redirect#84]
Using JavaScript's .innerHTML is considered unsafe by Mozilla which is why I created a new way of localizing an addon. You can see it in action at [nipos](https://notabug.org/nipos)' addon [Cloud Firewall](https://notabug.org/nipos/cloud-firewall).

Instead of an element like

```<h1 data-localize="__MSG_disableInvidious__">Invidious Redirects</h1>``` 

I'd write:

```<h1><i18n>disableInvidious</i18n></h1>```

in combination with the jQuery function

```
$(document).ready(function() {
	$('i18n').each(function(i, obj) {
		var msg = $(this).text();
		$(this).text(browser.i18n.getMessage(msg));
	});
 });
```

In my opinion, this approach is much easier than the existing one. So if you like it, @SimonBrazell, I'd take care of the implementation and make a pull request. What do you think?

**Comment by SimonBrazell** [comment]
Hi @realpixelcode I like this idea, I think it will be fairly easy to implement without the use of JQuery also, but I am actually using HTML in one of the localised messages:

```
"exceptionsDescription": {
    "message": "<p>Enter a URL or Regular Expression to be excluded from redirects.</p><p>All requests for or initiating from a URL that matches the exception will be excluded from redirects.</p><p><b>Note -</b> Supports JavaScript regular expressions, excluding the enclosing forward slashes.</p>",
    "description": "A description of the 'Exceptions' feature (options)."
  }
```
I'd need to split this one out into separate paragraphs or something to do the same, shame the translations are so inconvenient in extensions.

Also I wonder why Mozilla considers `innerHtml` unsafe when run from an extension?

**Comment by SimonBrazell** [comment]
Here is a solution that doesn't use `innerHtml` or JQuery and doesn't require changing the existing HTML:

```
window.browser = window.browser || window.chrome;

function localisePage() {
  // Localize using __MSG_***__ data tags
  var data = document.querySelectorAll("[data-localize]");

  for (var i in data)
    if (data.hasOwnProperty(i)) {
      var obj = data[i];
      var tag = obj.getAttribute("data-localize").toString();

      var msg = tag.replace(/__MSG_(\w+)__/g, function (_match, v1) {
        return v1 ? browser.i18n.getMessage(v1) : null;
      });

      if (msg && msg !== tag) obj.textContent = msg;
    }
}

localisePage();
```

Just using `textContent` instead, should have thought of that before 🙂 just need to fix up that one message with HTML tags inside.

**Comment by realpixelcode** [comment]
> I am actually using HTML in one of the localised messages:

Oh, right. Forgot that.

> Also I wonder why Mozilla considers `innerHtml` unsafe when run from an extension?

I have absolutely no clue

**Comment by SimonBrazell** [comment]
I'll do this in the next build, another user asked me to look at one of the localisation messages while I was at it anyway.

**Comment by SimonBrazell** [comment]
Just uploading a build including this now, but I realised I'm still using `innerHtml` elsewhere in the `options.js`, here's the message you receive on AMO when uploading a build using innerHTML:

> Unsafe assignment to innerHTML
> Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
