### ISSUE TITLE
Invidious embeds now autoplay?

### ISSUE THREAD

**Issue by narFnarF** [SimonBrazell/privacy-redirect#89]
This will be a very vague question. Sorry.

I'm wondering if something changed in the extention in the last month that could cause Invidious embedded videos to sometime autoplay. Or maybe it was something that changed on Invidious side? Or maybe in Youtube's embed code?

You can imagine how annoying it is to load a website with multiple embedded videos, and have all of them start playing at the same time. Often they aren't even visible on screen so I have to search everywhere to find them and pause them.

I don't have repro steps at the moment or any good URL to provide as exemple (I'll try to update this ticket if I do).

Am I the only one with this issue?

**Comment by SimonBrazell** [comment]
Hi @narFnarF this may be caused by the Invidious autoplay setting I added in a recent release, I don't think I set it to be on by default but perhaps I made a mistake, please check this in the advanced options menu, and try disabling it if it's on.

**Comment by SimonBrazell** [comment]
Actually just noticed a bug, it appears I've reversed the toggle, on make it not autoplay, off makes it autoplay... sorry I'll fix this in next release.

**Comment by gingerlime** [comment]
Also bumped into this issue with embedded videos autoplaying. In some cases, there might be several embeds on a page and they all start at once. My setting is not to autoplay

I noticed that when I access a page with autoplaying embeds, they start playing, but usually if I reload the same page, then they won't autoplay... maybe it was just a coincidence. EDIT: I'm not sure refreshing always helps. Maybe it won't autoplay the widget that's in the viewport? I'm not sure...

I'm using the FF extension with Firefox 96.0 (64-bit) on MacOS Big Sur
