### ISSUE TITLE
Avoid redirecting studio.youtube.com

### ISSUE THREAD

**Issue by narFnarF** [SimonBrazell/privacy-redirect#9]
I wonder if it would be possible to add an exception so that links to studio.youtube.com would not redirect to invidious.

As the owner of a channel, I would like to be able to keep editing my videos and livestreams.

Here's some example URLs
* https://studio.youtube.com/channel/UC45wqb_2-hGWlhWJp_XipkQ
* https://studio.youtube.com/channel/UC45wqb_2-hGWlhWJp_XipkQ/videos/upload
* https://studio.youtube.com/channel/UC45wqb_2-hGWlhWJp_XipkQ/videos/upload?filter=%5B%5D&sort=%7B%22columnType%22%3A%22date%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D
(you won't be able to access the content because it requires login. I'm only providing them for example)

I understand that I can just deactivate the redirection temporarily when I need to access Youtube Studio, but that would be a little nice improvement. Maybe as an option?

Thanks for this otherwise excellent extension! :)

**Comment by SimonBrazell** [comment]
Hi @narFnarF, this sounds like a great idea, I think any feature that isn't implemented in the alternative front-ends should not be redirected, and this seems like a good candidate for that rule.

Do you think anyone would ever have a reason to redirect `studio.youtube.com/...` to the alternative? If not I wouldn't bother with the setting I think.

**Comment by SimonBrazell** [comment]
Included in [v1.1.6](https://github.com/SimonBrazell/privacy-redirect/releases/tag/v1.1.6), which is currently pending release on the stores.

**Comment by narFnarF** [comment]
> Do you think anyone would ever have a reason to redirect `studio.youtube.com/...` to the alternative? If not I wouldn't bother with the setting I think.

I think your assumption is correct. Worst case, someone else could open a ticket in the future.

Thanks for the fix! :)
