### ISSUE TITLE
Add more bibliogram instances

### ISSUE THREAD

**Issue by tiotrom** [SimonBrazell/privacy-redirect#90]
Here are a few of them https://git.sr.ht/~cadence/bibliogram-docs/tree/master/docs/Instances.md - right now the one that's default almost never works. Cheers!

**Comment by tiotrom** [comment]
Well I didn't realize there are many instances since the menu doesnt work well in the settings. If you click the menu you should see a drop-down of all instances, instead you only see the current instance. Only after you delete (as in delete the text) from the drop down form, it may work to display the instances, but at times it does not. So, I strongly suggest you to improve that. I am doing webdesign for 15 years now and I am a very online oriented creature testing apps, operating systems and the like. If I failed to see that there are more than one instances, I am sure others do too.
![Peek 2020-08-24 14-36](https://user-images.githubusercontent.com/34804533/91045546-5866f480-e617-11ea-9556-51428d1cd695.gif)

**Comment by SimonBrazell** [comment]
> So, I strongly suggest you to improve that. I am doing webdesign for 15 years now and I am a very online oriented creature testing apps, operating systems and the like.

Hi @tiotrom you may have noticed there hasn't been much activity on this repo lately, I'm pretty short on time of late, very busy with other dev work, and would appreciate some help with features like this and others if you're interested?

I originally used the built in HTML `datalist` to provide this feature, however I discovered that the add-on preferences pages don't support `datalist` for some reason... so I had to roll my own solution, basically emulating the functionality of a native datalist, which includes a search feature. It is this search feature that narrows down the list based on what is currently in the input field, so when there is a URL already in there it only shows others that match that one, which is what is causing this problem. 

I think the code could be slightly modified to only show the narrowed down list when the user types something, and show the full list on the initial click instead?

**Comment by tiotrom** [comment]
> I think the code could be slightly modified to only show the narrowed down list when the user types something, and show the full list on the initial click instead?

I think that would be the best.

> Hi @tiotrom you may have noticed there hasn't been much activity on this repo lately, I'm pretty short on time of late, very busy with other dev work, and would appreciate some help with features like this and others if you're interested?

Unfortunately I do not know how I can help. I am doing mostly webdesign, the design part, not the coding part...

**Comment by SimonBrazell** [comment]
> Unfortunately I do not know how I can help. I am doing mostly webdesign, the design part, not the coding part...

Oh right, no worries I'll see what I can do.

**Comment by tiotrom** [comment]
In any case you created a wonderful addon. We made a custom Linux distro TROMjaro, and we are adding such things to our distro by default so I am testing this addon to see if it is reliable enough to add it as default. I wish I could help. Others who are involved with TROMjaro are too buys with other things .... but I am here to test stuff.

**Comment by SimonBrazell** [comment]
I need to do a build to address the shutdown of invidio.us in the next few days so I'll see if I can do something about the preferences while I'm at it.

**Comment by tiotrom** [comment]
Sounds great!

**Comment by SimonBrazell** [comment]
Okay I think I've addressed the issue with dropdown selects now, just to be clear was this the reason you reported the lack of instances? Or do you still want more instances added now that you found them?

**Comment by SimonBrazell** [comment]
Same goes for the other instance related issues you've opened. I'll wait before releasing this latest change just in case.

**Comment by tiotrom** [comment]
Awesome! Yes this was the reason I reported. I didn't realize there are many of them. Thanks a lot! Great job

**Comment by SimonBrazell** [comment]
Oh great, no worries I'll push these changes live now.

**Comment by tiotrom** [comment]
Wonderful!
