### ISSUE TITLE
Invidious redirect doesn't work

### ISSUE THREAD

**Issue by stemy2** [SimonBrazell/privacy-redirect#95]
Hello,

Invidious redirect doesn't work anymore. When it should, instead of the said video, i have blank spaces where i should have embedded videos and a youtube page instead of invidious page, both of them loading indefinitely. And all that with working instances.

**Comment by stemy2** [comment]
Fount it ! It was another add-on's fault.

**Comment by SimonBrazell** [comment]
Good to hear! Which add-on was it? Might be good to know for future reference.

**Comment by stemy2** [comment]
Peertubeify, the peertube search instance i had set didn't work, so it blocked the action of invidious redirect. It's working again since i replaced it by an actually working instance.
