### ISSUE TITLE
Bibliogram: handle /igtv/, /tv/ and /reel/

### ISSUE THREAD

**Issue by B0pol** [SimonBrazell/privacy-redirect#99]
According to [this commit](https://git.sr.ht/~cadence/bibliogram/commit/c6ea5ae8e4e5f21dd33a62afeebbf8df8c534354), they should be treated like a post, therefore they should not be redirected to /u/tv/, /u/reel/ …

One example:
https://www.instagram.com/tv/CDjb45uA51d/?utm_source=ig_embed&utm_campaign=loading

Expected -> https://bibliogram.art/tv/CDjb45uA51d
Actual -> https://bibliogram.art/u/tv/CDjb45uA51d

**Comment by SimonBrazell** [comment]
Thanks for letting me know @B0pol I'll fix this up in the next release.
